server:
  port: 8085

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hospital.payment.entity
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  packages-to-scan: com.hospital.payment
  api-docs:
    enabled: true

logging:
  level:
    com.hospital: DEBUG
