allowBuilds:
  vue-demi: true
overrides:
  '@win-design-next/icons-vue': file:vendor/win-design-next-icons-vue-1.0.4.tgz
  '@win-design-next/iconi-vue': file:vendor/win-design-next-iconi-vue-1.0.4.tgz
