-- ============================================================
-- medsupply_db V10：线上购药配送（迭代13 K2）
--   delivery 配送单：处方流转院内药房 → 创建配送单 → 发货 → 送达
-- 幂等：user_tables 探测后创建
-- ============================================================

DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'DELIVERY';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE delivery (
            id              NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
            delivery_no     VARCHAR2(32 CHAR)   NOT NULL,
            prescription_id NUMBER(19)          NOT NULL,
            patient_id      NUMBER(19)          NOT NULL,
            patient_name    VARCHAR2(50 CHAR)   DEFAULT NULL,
            drug_summary    VARCHAR2(500 CHAR)  DEFAULT NULL,
            receiver_name   VARCHAR2(50 CHAR)   NOT NULL,
            receiver_phone  VARCHAR2(20 CHAR)   NOT NULL,
            address         VARCHAR2(300 CHAR)  NOT NULL,
            status          VARCHAR2(20 CHAR)   DEFAULT ''CREATED'' NOT NULL,
            operator_id     NUMBER(19)          DEFAULT NULL,
            create_time     TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            dispatch_time   TIMESTAMP           DEFAULT NULL,
            deliver_time    TIMESTAMP           DEFAULT NULL,
            CONSTRAINT pk_delivery PRIMARY KEY (id),
            CONSTRAINT uk_delivery_no UNIQUE (delivery_no)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_delivery_patient ON delivery (patient_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_delivery_status ON delivery (status)';
    END IF;
END;
/
COMMENT ON TABLE delivery IS '线上购药配送单（K2）: status=CREATED已创建/DISPATCHED已发货/DELIVERED已送达; 处方信息冗余（跨库不校验）';
