-- =====================================================================
-- V11: 迭代14 L1 耗材管理 + L2 设备台账（medsupply）
-- 幂等：user_tables 探测后建表
-- =====================================================================

-- L1 耗材字典
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'CONSUMABLE';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE consumable (
      id            NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
      code          VARCHAR2(32 CHAR) NOT NULL,
      name          VARCHAR2(100 CHAR) NOT NULL,
      specification VARCHAR2(100 CHAR),
      unit          VARCHAR2(20 CHAR),
      price         NUMBER(12,2)      DEFAULT 0,
      stock         NUMBER(10)        DEFAULT 0 NOT NULL,
      safety_stock  NUMBER(10)        DEFAULT 0 NOT NULL,
      status        VARCHAR2(20 CHAR) DEFAULT ''ACTIVE'' NOT NULL,
      create_time   TIMESTAMP         DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_consumable PRIMARY KEY (id),
      CONSTRAINT uq_consumable_code UNIQUE (code),
      CONSTRAINT ck_consumable_status CHECK (status IN (''ACTIVE'', ''DISABLED''))
    )';
  END IF;
END;
/

-- L1 耗材出入库流水
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'CONSUMABLE_RECORD';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE consumable_record (
      id            NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      consumable_id NUMBER(19)       NOT NULL,
      record_type   VARCHAR2(10 CHAR) NOT NULL,
      quantity      NUMBER(10)       NOT NULL,
      operator_id   NUMBER(19),
      operator_name VARCHAR2(50 CHAR),
      remark        VARCHAR2(200 CHAR),
      create_time   TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_consumable_record PRIMARY KEY (id),
      CONSTRAINT ck_consumable_record_type CHECK (record_type IN (''IN'', ''OUT'')),
      CONSTRAINT fk_crecord_consumable FOREIGN KEY (consumable_id) REFERENCES consumable (id)
    )';
  END IF;
END;
/

CREATE INDEX idx_crecord_consumable ON consumable_record (consumable_id);

-- L2 设备台账
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'EQUIPMENT';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE equipment (
      id                 NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
      code               VARCHAR2(32 CHAR) NOT NULL,
      name               VARCHAR2(100 CHAR) NOT NULL,
      model              VARCHAR2(100 CHAR),
      location           VARCHAR2(100 CHAR),
      status             VARCHAR2(20 CHAR) DEFAULT ''IDLE'' NOT NULL,
      buy_date           DATE,
      last_maintain_date DATE,
      remark             VARCHAR2(200 CHAR),
      create_time        TIMESTAMP         DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_equipment PRIMARY KEY (id),
      CONSTRAINT uq_equipment_code UNIQUE (code),
      CONSTRAINT ck_equipment_status CHECK (status IN (''USING'', ''IDLE'', ''REPAIR'', ''SCRAP''))
    )';
  END IF;
END;
/
