-- ============================================================
-- medsupply_db V1__init.sql（Oracle 19c 版，迭代6.5 迁移）
-- 医辅物资服务：7 张表
-- ============================================================

-- ==================== 1. drug（药品目录表） ====================
CREATE TABLE drug (
    id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    drug_code       VARCHAR2(50 CHAR)  NOT NULL,
    drug_name       VARCHAR2(200 CHAR) NOT NULL,
    generic_name    VARCHAR2(200 CHAR) DEFAULT NULL,
    specification   VARCHAR2(100 CHAR) DEFAULT NULL,
    dosage_form     VARCHAR2(50 CHAR)  DEFAULT NULL,
    manufacturer    VARCHAR2(200 CHAR) DEFAULT NULL,
    reference_price NUMBER(10,2)       DEFAULT 0.00,
    unit            VARCHAR2(20 CHAR)  DEFAULT NULL,
    description     CLOB,
    status          NUMBER(3)          DEFAULT 1,
    create_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_drug PRIMARY KEY (id),
    CONSTRAINT uk_drug_code UNIQUE (drug_code)
);
COMMENT ON TABLE drug IS '药品目录表';

-- ==================== 2. drug_inventory（药品库存表） ====================
CREATE TABLE drug_inventory (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    drug_id            NUMBER(19) NOT NULL,
    current_stock      NUMBER(10) DEFAULT 0,
    min_threshold      NUMBER(10) DEFAULT 10,
    version            NUMBER(10) DEFAULT 0,
    last_stockin_time  TIMESTAMP  DEFAULT NULL,
    last_stockout_time TIMESTAMP  DEFAULT NULL,
    create_time        TIMESTAMP  DEFAULT SYSDATE NOT NULL,
    update_time        TIMESTAMP  DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_drug_inventory PRIMARY KEY (id),
    CONSTRAINT uk_inventory_drug UNIQUE (drug_id)
);
COMMENT ON TABLE drug_inventory IS '药品库存表';

-- ==================== 3. drug_inventory_log（库存流水表） ====================
CREATE TABLE drug_inventory_log (
    id               NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    drug_id          NUMBER(19)         NOT NULL,
    change_type      VARCHAR2(20 CHAR)  NOT NULL,
    change_quantity  NUMBER(10)         NOT NULL,
    before_stock     NUMBER(10)         NOT NULL,
    after_stock      NUMBER(10)         NOT NULL,
    related_order_id NUMBER(19)         DEFAULT NULL,
    operator_id      NUMBER(19)         DEFAULT NULL,
    remark           VARCHAR2(500 CHAR) DEFAULT NULL,
    create_time      TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_drug_inventory_log PRIMARY KEY (id)
);
CREATE INDEX idx_inv_log_drug ON drug_inventory_log (drug_id);
CREATE INDEX idx_inv_log_create_time ON drug_inventory_log (create_time);
COMMENT ON TABLE drug_inventory_log IS '库存流水表';

-- ==================== 4. exam_item（检查检验项目表） ====================
CREATE TABLE exam_item (
    id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    item_code       VARCHAR2(50 CHAR)  NOT NULL,
    item_name       VARCHAR2(200 CHAR) NOT NULL,
    item_type       VARCHAR2(50 CHAR)  NOT NULL,
    reference_price NUMBER(10,2)       DEFAULT 0.00,
    exec_dept       VARCHAR2(100 CHAR) DEFAULT NULL,
    precautions     CLOB,
    status          NUMBER(3)          DEFAULT 1,
    create_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_exam_item PRIMARY KEY (id),
    CONSTRAINT uk_exam_item_code UNIQUE (item_code)
);
COMMENT ON TABLE exam_item IS '检查检验项目表';

-- ==================== 5. exam_application（检查申请表） ====================
CREATE TABLE exam_application (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    application_no    VARCHAR2(32 CHAR)  NOT NULL,
    medical_record_id NUMBER(19)         NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    doctor_id         NUMBER(19)         NOT NULL,
    exam_item_id      NUMBER(19)         NOT NULL,
    exam_item_name    VARCHAR2(200 CHAR) NOT NULL,
    item_type         VARCHAR2(50 CHAR)  NOT NULL,
    apply_remark      VARCHAR2(500 CHAR) DEFAULT NULL,
    status            VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_exam_application PRIMARY KEY (id),
    CONSTRAINT uk_exam_application_no UNIQUE (application_no)
);
CREATE INDEX idx_exam_app_patient ON exam_application (patient_id);
CREATE INDEX idx_exam_app_status ON exam_application (status);
COMMENT ON TABLE exam_application IS '检查申请表';

-- ==================== 6. exam_report（检查报告表） ====================
CREATE TABLE exam_report (
    id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    application_id  NUMBER(19)         NOT NULL,
    patient_id      NUMBER(19)         NOT NULL,
    report_desc     CLOB,
    report_result   CLOB,
    attachment_url  VARCHAR2(500 CHAR) DEFAULT NULL,
    attachment_name VARCHAR2(200 CHAR) DEFAULT NULL,
    operator_id     NUMBER(19)         DEFAULT NULL,
    status          VARCHAR2(20 CHAR)  DEFAULT 'DRAFT' NOT NULL,
    complete_time   TIMESTAMP          DEFAULT NULL,
    create_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_exam_report PRIMARY KEY (id),
    CONSTRAINT uk_exam_report_application UNIQUE (application_id)
);
CREATE INDEX idx_exam_report_patient ON exam_report (patient_id);
COMMENT ON TABLE exam_report IS '检查报告表';

-- ==================== 7. drug_dispense（发药记录表） ====================
CREATE TABLE drug_dispense (
    id                    NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    prescription_id       NUMBER(19)         NOT NULL,
    patient_id            NUMBER(19)         NOT NULL,
    status                VARCHAR2(20 CHAR)  DEFAULT 'PENDING_REVIEW' NOT NULL,
    review_operator_id    NUMBER(19)         DEFAULT NULL,
    review_comment        VARCHAR2(500 CHAR) DEFAULT NULL,
    review_time           TIMESTAMP          DEFAULT NULL,
    dispense_operator_id  NUMBER(19)         DEFAULT NULL,
    dispense_time         TIMESTAMP          DEFAULT NULL,
    create_time           TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_drug_dispense PRIMARY KEY (id),
    CONSTRAINT uk_dispense_prescription UNIQUE (prescription_id)
);
CREATE INDEX idx_dispense_patient ON drug_dispense (patient_id);
CREATE INDEX idx_dispense_status ON drug_dispense (status);
COMMENT ON TABLE drug_dispense IS '发药记录表';
