-- ============================================================
-- medsupply_db V5：门诊输液 + 检查执行登记（Oracle 19c 版）
-- 说明：对齐真实医院门诊业务
--   1. 新增 infusion_order（输液单）、infusion_record（输液执行记录）
--   2. exam_application 增加检查执行登记字段
-- ============================================================

-- ==================== 8. infusion_order（输液单表） ====================
-- 医生开具输液医嘱后生成输液单，由护士站执行
CREATE TABLE infusion_order (
    id                 NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    infusion_no        VARCHAR2(32 CHAR)  NOT NULL,
    medical_record_id  NUMBER(19)         NOT NULL,
    patient_id         NUMBER(19)         NOT NULL,
    doctor_id          NUMBER(19)         NOT NULL,
    drug_id            NUMBER(19)         NOT NULL,
    drug_name          VARCHAR2(200 CHAR) NOT NULL,
    dosage             VARCHAR2(50 CHAR)  NOT NULL,
    usage_method       VARCHAR2(50 CHAR)  NOT NULL,
    frequency          VARCHAR2(50 CHAR)  NOT NULL,
    days               NUMBER(10)         NOT NULL,
    skin_test_required NUMBER(3)          DEFAULT 0,
    unit_price         NUMBER(10,2)       NOT NULL,
    total_amount       NUMBER(10,2)       NOT NULL,
    pay_status         VARCHAR2(20 CHAR)  DEFAULT 'UNPAID' NOT NULL,
    status             VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    create_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_infusion_order PRIMARY KEY (id),
    CONSTRAINT uk_infusion_no UNIQUE (infusion_no)
);
CREATE INDEX idx_infusion_patient ON infusion_order (patient_id);
CREATE INDEX idx_infusion_status ON infusion_order (status);
COMMENT ON TABLE infusion_order IS '输液单表';

-- ==================== 9. infusion_record（输液执行记录表） ====================
-- 护士每次执行输液操作时生成一条记录
CREATE TABLE infusion_record (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    infusion_order_id NUMBER(19)         NOT NULL,
    record_type       VARCHAR2(20 CHAR)  NOT NULL,
    record_content    VARCHAR2(500 CHAR) DEFAULT NULL,
    skin_test_result  VARCHAR2(20 CHAR)  DEFAULT NULL,
    drop_rate         NUMBER(10)         DEFAULT NULL,
    operator_id       NUMBER(19)         DEFAULT NULL,
    operator_name     VARCHAR2(50 CHAR)  DEFAULT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_infusion_record PRIMARY KEY (id)
);
CREATE INDEX idx_infusion_record_order ON infusion_record (infusion_order_id);
COMMENT ON TABLE infusion_record IS '输液执行记录表';

-- ==================== exam_application 增加执行登记字段 ====================
ALTER TABLE exam_application
    ADD (exec_time        TIMESTAMP  DEFAULT NULL,
         exec_operator_id NUMBER(19) DEFAULT NULL);
