-- ============================================================
-- medsupply_db V7：危急值 + 处方点评（Oracle 19c 版，迭代6 功能补全）
-- 说明：
--   1. critical_value 危急值：检验/检查结果命中阈值 → 上报 → 复核闭环
--   2. prescription_review 处方点评：药师对处方点评（合理/不合理/问题分类）
-- ============================================================

-- 1. 危急值表
CREATE TABLE critical_value (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    report_id         NUMBER(19)         NOT NULL,
    application_id    NUMBER(19)         NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    item_name         VARCHAR2(200 CHAR) NOT NULL,
    result_value      VARCHAR2(200 CHAR) NOT NULL,
    reference_range   VARCHAR2(200 CHAR) DEFAULT NULL,
    critical_level    VARCHAR2(20 CHAR)  DEFAULT 'HIGH' NOT NULL,
    status            VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    reporter_id       NUMBER(19)         DEFAULT NULL,
    confirm_doctor_id NUMBER(19)         DEFAULT NULL,
    confirm_comment   VARCHAR2(500 CHAR) DEFAULT NULL,
    confirm_time      TIMESTAMP          DEFAULT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_critical_value PRIMARY KEY (id)
);
CREATE INDEX idx_critical_status ON critical_value (status);
CREATE INDEX idx_critical_patient ON critical_value (patient_id);
CREATE INDEX idx_critical_report ON critical_value (report_id);
COMMENT ON TABLE critical_value IS '危急值表';

-- 2. 处方点评表
CREATE TABLE prescription_review (
    id              NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    prescription_id NUMBER(19)          NOT NULL,
    patient_id      NUMBER(19)          NOT NULL,
    pharmacist_id   NUMBER(19)          NOT NULL,
    rating          VARCHAR2(20 CHAR)   DEFAULT 'REASONABLE' NOT NULL,
    problem_type    VARCHAR2(100 CHAR)  DEFAULT NULL,
    review_comment  VARCHAR2(1000 CHAR) DEFAULT NULL,
    create_time     TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_prescription_review PRIMARY KEY (id)
);
CREATE INDEX idx_prescription_review_prescription ON prescription_review (prescription_id);
CREATE INDEX idx_prescription_review_pharmacist ON prescription_review (pharmacist_id);
COMMENT ON TABLE prescription_review IS '处方点评表';
