-- =============================================================
-- V8: 药事管理扩展（迭代7 B1/B3/B5~B10）
--   B1 药品三分类；B5 药库批次效期；B6 退药；B7 调拨；
--   B8 麻精管控+五专登记；B9 CDSS 规则；B10 抗菌授权；B3 代煎订单
-- 方言：Oracle 19c（IDENTITY/VARCHAR2 CHAR/TIMESTAMP DEFAULT SYSDATE）
-- =============================================================

-- ── B1 药品目录扩展：三分类 ──
ALTER TABLE drug ADD (drug_type VARCHAR2(20 CHAR) DEFAULT 'WESTERN' NOT NULL);
COMMENT ON COLUMN drug.drug_type IS '药品分类: WESTERN-西药 / CHINESE_PATENT-中成药 / HERBAL-中药饮片';

-- ── B8 麻精药品管控级别 ──
ALTER TABLE drug ADD (control_level VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL);
COMMENT ON COLUMN drug.control_level IS '管控级别: NORMAL-普通 / NARCOTIC-麻醉药品 / PSYCHIATRIC_1-第一类精神 / PSYCHIATRIC_2-第二类精神';

-- ── B10 抗菌药物分级（NULL 表示非抗菌药）──
ALTER TABLE drug ADD (antibiotic_level VARCHAR2(20 CHAR));
COMMENT ON COLUMN drug.antibiotic_level IS '抗菌分级: NULL-非抗菌 / NON_RESTRICTED-非限制使用 / RESTRICTED-限制使用 / SPECIAL-特殊使用';

-- ── B5 药品批次表（采购入库/供货商/批号/效期）──
CREATE TABLE drug_batch (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id        NUMBER(19)        NOT NULL,
  batch_no       VARCHAR2(50 CHAR) NOT NULL,
  supplier       VARCHAR2(100 CHAR),
  quantity       NUMBER(10) DEFAULT 0 NOT NULL,
  production_date DATE,
  expiry_date    DATE              NOT NULL,
  inbound_type   VARCHAR2(20 CHAR) DEFAULT 'PURCHASE' NOT NULL,
  status         VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  operator_id    NUMBER(19),
  create_time    TIMESTAMP DEFAULT SYSDATE,
  update_time    TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE drug_batch IS '药品批次（药库维度，B5）: inbound_type=PURCHASE采购/RETURN退药回冲/TRANSFER调拨入; status=ACTIVE/EXHAUSTED耗尽/SCRAPPED报损';
CREATE INDEX idx_batch_drug ON drug_batch (drug_id);
CREATE INDEX idx_batch_expiry ON drug_batch (expiry_date);

-- ── B6 退药单（发药后退药冲账，库存回冲）──
CREATE TABLE drug_return (
  id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_no     VARCHAR2(40 CHAR) NOT NULL,
  prescription_id NUMBER(19),
  patient_id    NUMBER(19)        NOT NULL,
  drug_id       NUMBER(19)        NOT NULL,
  quantity      NUMBER(10)        NOT NULL,
  refund_amount NUMBER(12,2)      NOT NULL,
  reason        VARCHAR2(200 CHAR),
  operator_id   NUMBER(19),
  status        VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
  create_time   TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE drug_return IS '退药单（B6）: 发药后退药，库存回冲+金额冲账';
CREATE INDEX idx_return_rx ON drug_return (prescription_id);

-- ── B7 药品调拨单（药库→药房→科室）──
CREATE TABLE drug_transfer (
  id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_no  VARCHAR2(40 CHAR) NOT NULL,
  drug_id      NUMBER(19)        NOT NULL,
  quantity     NUMBER(10)        NOT NULL,
  from_location VARCHAR2(20 CHAR) DEFAULT 'WAREHOUSE' NOT NULL,
  to_location  VARCHAR2(20 CHAR) DEFAULT 'PHARMACY' NOT NULL,
  batch_no     VARCHAR2(50 CHAR),
  operator_id  NUMBER(19),
  status       VARCHAR2(20 CHAR) DEFAULT 'COMPLETED' NOT NULL,
  create_time  TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE drug_transfer IS '调拨单（B7）: from/to = WAREHOUSE药库 / PHARMACY药房 / DEPT临床科室';
CREATE INDEX idx_transfer_drug ON drug_transfer (drug_id);

-- ── B8 麻精药品五专登记册（专人/专账流水，入出存全留痕）──
CREATE TABLE narcotic_register (
  id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_id         NUMBER(19)        NOT NULL,
  prescription_id NUMBER(19),
  patient_id      NUMBER(19),
  action          VARCHAR2(20 CHAR) NOT NULL,
  quantity        NUMBER(10)        NOT NULL,
  balance         NUMBER(10)        NOT NULL,
  operator_id     NUMBER(19),
  remark          VARCHAR2(200 CHAR),
  create_time     TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE narcotic_register IS '麻精药品专用登记（B8 五专之专账）: action=INBOUND入库/OUTBOUND发药/RETURN退药/SCRAP报损, balance=登记后结存';
CREATE INDEX idx_narcotic_drug ON narcotic_register (drug_id);

-- ── B9 CDSS 合理用药规则表 ──
CREATE TABLE drug_rule (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_type      VARCHAR2(30 CHAR) NOT NULL,
  drug_id        NUMBER(19),
  paired_drug_id NUMBER(19),
  max_single_dose NUMBER(10,2),
  max_daily_dose  NUMBER(10,2),
  severity       VARCHAR2(20 CHAR) DEFAULT 'WARN' NOT NULL,
  description    VARCHAR2(300 CHAR),
  status         NUMBER(3) DEFAULT 1 NOT NULL,
  create_time    TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE drug_rule IS 'CDSS 规则（B9）: rule_type=MAX_DOSE剂量上限/DRUG_DUPLICATE重复用药/DRUG_CONFLICT配伍禁忌/PREGNANCY妊娠禁忌; severity=BLOCK拦截/WARN警告';
CREATE INDEX idx_rule_drug ON drug_rule (drug_id);

-- ── B10 抗菌药物医生授权表 ──
CREATE TABLE doctor_antibiotic_auth (
  id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id   NUMBER(19)        NOT NULL,
  max_level   VARCHAR2(20 CHAR) NOT NULL,
  approver_id NUMBER(19),
  status      NUMBER(3) DEFAULT 1 NOT NULL,
  create_time TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT uk_doc_antib UNIQUE (doctor_id)
);
COMMENT ON TABLE doctor_antibiotic_auth IS '抗菌药物分级授权（B10）: max_level=NON_RESTRICTED/RESTRICTED/SPECIAL，开方时校验医生授权上限';

-- ── B3 中药代煎订单（自煎/代煎 + 状态机 + 取药凭证）──
CREATE TABLE decoction_order (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no       VARCHAR2(40 CHAR) NOT NULL,
  prescription_id NUMBER(19)       NOT NULL,
  patient_id     NUMBER(19)        NOT NULL,
  doses          NUMBER(3) DEFAULT 7 NOT NULL,
  decoction_type VARCHAR2(20 CHAR) DEFAULT 'SELF' NOT NULL,
  status         VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  pickup_code    VARCHAR2(20 CHAR),
  fee_amount     NUMBER(12,2) DEFAULT 0,
  remark         VARCHAR2(200 CHAR),
  create_time    TIMESTAMP DEFAULT SYSDATE,
  update_time    TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE decoction_order IS '中药代煎订单（B3）: decoction_type=SELF自煎/HOSPITAL代煎; status=PENDING待煎/DECOCTING煎制中/READY待取药/DISPENSED已发药/CANCELLED已取消; pickup_code=取药凭证码';
CREATE INDEX idx_decoction_rx ON decoction_order (prescription_id);
