-- =============================================================
-- V9: 检验 LIS + 影像中心（迭代8 C2~C4/D1~D6）
--   C2 标本采集；C3 检验结果结构化明细；D1 检查预约报到；
--   D2 影像序列（MinIO）；D4 报告模板；D5 modality 类别扩展；
--   结构化报告字段（所见/印象）
-- 方言：Oracle 19c
-- =============================================================

-- ── C2 标本采集登记（采血确认 + 标本号条码 + 核收状态机）──
CREATE TABLE specimen (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  specimen_no    VARCHAR2(40 CHAR) NOT NULL,
  application_id NUMBER(19)        NOT NULL,
  patient_id     NUMBER(19)        NOT NULL,
  specimen_type  VARCHAR2(20 CHAR) DEFAULT 'BLOOD' NOT NULL,
  container      VARCHAR2(30 CHAR),
  collect_site   VARCHAR2(50 CHAR),
  status         VARCHAR2(20 CHAR) DEFAULT 'COLLECTED' NOT NULL,
  collector_id   NUMBER(19),
  collect_time   TIMESTAMP DEFAULT SYSDATE,
  receiver_id    NUMBER(19),
  receive_time   TIMESTAMP,
  remark         VARCHAR2(200 CHAR),
  create_time    TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE specimen IS '标本采集（C2）: specimen_type=BLOOD血/URINE尿/STOOL便/SPUTUM痰/OTHER; status=COLLECTED已采集/RECEIVED核收/REJECTED拒收/TESTING检测中';
CREATE INDEX idx_specimen_app ON specimen (application_id);
CREATE UNIQUE INDEX uk_specimen_no ON specimen (specimen_no);

-- ── C3 检验结果结构化明细（项目/结果/单位/参考范围/↑↓标志）──
CREATE TABLE result_item (
  id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id     NUMBER(19)        NOT NULL,
  item_code     VARCHAR2(30 CHAR),
  item_name     VARCHAR2(60 CHAR) NOT NULL,
  result_value  VARCHAR2(60 CHAR) NOT NULL,
  unit          VARCHAR2(30 CHAR),
  ref_range     VARCHAR2(60 CHAR),
  abnormal_flag VARCHAR2(10 CHAR),
  sort_order    NUMBER(3) DEFAULT 0,
  create_time   TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE result_item IS '检验结果明细（C3）: 挂 exam_report.id，化验单按行渲染；abnormal_flag=↑↑/H/L/正常留空';
CREATE INDEX idx_result_report ON result_item (report_id);

-- ── D1 检查预约与登记报到 ──
CREATE TABLE exam_reservation (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id NUMBER(19)        NOT NULL,
  patient_id     NUMBER(19)        NOT NULL,
  reserve_date   DATE              NOT NULL,
  time_slot      VARCHAR2(20 CHAR) NOT NULL,
  room           VARCHAR2(30 CHAR),
  status         VARCHAR2(20 CHAR) DEFAULT 'BOOKED' NOT NULL,
  checkin_time   TIMESTAMP,
  create_time    TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE exam_reservation IS '检查预约（D1）: status=BOOKED已约/CHECKED_IN已报到/DONE已完成/CANCELLED已取消';
CREATE INDEX idx_examresv_app ON exam_reservation (application_id);
CREATE INDEX idx_examresv_date ON exam_reservation (reserve_date);

-- ── D2 影像序列（检查号关联 JPG 序列 → MinIO）──
CREATE TABLE image_series (
  id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_no      VARCHAR2(40 CHAR) NOT NULL,
  application_id NUMBER(19)        NOT NULL,
  patient_id     NUMBER(19)        NOT NULL,
  modality       VARCHAR2(20 CHAR) DEFAULT 'DX' NOT NULL,
  description    VARCHAR2(100 CHAR),
  image_count    NUMBER(5) DEFAULT 0,
  object_keys    CLOB,
  upload_by      NUMBER(19),
  create_time    TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE image_series IS '影像序列（D2/D3）: modality=DX摄影/CT/MR/US超声/ENDO内镜/PATH病理/ECG心电; object_keys=MinIO 对象 key 的 JSON 数组';
CREATE INDEX idx_series_app ON image_series (application_id);
CREATE UNIQUE INDEX uk_series_no ON image_series (series_no);

-- ── D4 报告模板字典（所见/印象，按类别与部位）──
CREATE TABLE report_template (
  id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modality      VARCHAR2(20 CHAR) NOT NULL,
  body_part     VARCHAR2(50 CHAR),
  template_type VARCHAR2(20 CHAR) DEFAULT 'FINDING' NOT NULL,
  content       CLOB               NOT NULL,
  status        NUMBER(3) DEFAULT 1 NOT NULL,
  create_time   TIMESTAMP DEFAULT SYSDATE
);
COMMENT ON TABLE report_template IS '报告模板（D4）: template_type=FINDING所见/CONCLUSION印象; body_part 空=通用';

-- ── D5 检查项目类别扩展（modality 影像学检查类别）──
ALTER TABLE exam_item ADD (modality VARCHAR2(20 CHAR));
COMMENT ON COLUMN exam_item.modality IS '检查类别（D5）: DX/CT/MR/US/ENDO/PATH/ECG，检验类为空';

-- ── D4 结构化影像报告字段（所见/印象）──
ALTER TABLE exam_report ADD (findings CLOB);
COMMENT ON COLUMN exam_report.findings IS '结构化-所见（D4）';
ALTER TABLE exam_report ADD (conclusion VARCHAR2(500 CHAR));
COMMENT ON COLUMN exam_report.conclusion IS '结构化-印象（D4）';
