-- ============================================================
-- ai_db V1__init.sql（Oracle 19c 版，迭代6.5 迁移）
-- AI辅助服务：1 张表
-- ============================================================

-- ==================== 1. ai_call_log（AI调用日志表） ====================
CREATE TABLE ai_call_log (
    id                  NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    patient_id          NUMBER(19)         NOT NULL,
    symptom_input       VARCHAR2(500 CHAR) NOT NULL,
    model_name          VARCHAR2(50 CHAR)  DEFAULT NULL,
    request_text        CLOB,
    response_text       CLOB,
    recommend_dept_id   NUMBER(19)         DEFAULT NULL,
    recommend_dept_name VARCHAR2(100 CHAR) DEFAULT NULL,
    confidence          NUMBER(5,2)        DEFAULT 0.00,
    is_degraded         NUMBER(3)          DEFAULT 0,
    degraded_reason     VARCHAR2(50 CHAR)  DEFAULT NULL,
    execution_time_ms   NUMBER(19)         DEFAULT NULL,
    status              NUMBER(3)          DEFAULT 1,
    error_message       VARCHAR2(500 CHAR) DEFAULT NULL,
    create_time         TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_ai_call_log PRIMARY KEY (id)
);
CREATE INDEX idx_ai_call_patient ON ai_call_log (patient_id);
CREATE INDEX idx_ai_call_create_time ON ai_call_log (create_time);
COMMENT ON TABLE ai_call_log IS 'AI调用日志表';
