-- =====================================================================
-- V3: 迭代15 B1 爽约预测记录（ai）
-- 幂等：user_tables 探测后建表
-- =====================================================================

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'NO_SHOW_PREDICTION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE no_show_prediction (
      id             NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      patient_id     NUMBER(19)       NOT NULL,
      appointment_id NUMBER(19)       NOT NULL,
      score          NUMBER(5,4)      NOT NULL,
      risk_level     VARCHAR2(10 CHAR) NOT NULL,
      factors        VARCHAR2(500 CHAR),
      create_time    TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_no_show_prediction PRIMARY KEY (id),
      CONSTRAINT ck_noshow_level CHECK (risk_level IN (''LOW'', ''MEDIUM'', ''HIGH''))
    )';
  END IF;
END;
/

CREATE INDEX idx_noshow_patient ON no_show_prediction (patient_id);
