-- =====================================================================
-- V4: 迭代16 B2 AI智能层（ai：多轮问诊会话 / 通用预测留痕）
-- 幂等：user_tables 探测后建表
-- =====================================================================

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'AI_CONSULT_SESSION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE ai_consult_session (
      id            NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      session_no    VARCHAR2(32 CHAR) NOT NULL,
      patient_id    NUMBER(19)       NOT NULL,
      symptom       VARCHAR2(500 CHAR) NOT NULL,
      messages      CLOB,
      rounds        NUMBER(5)        DEFAULT 0 NOT NULL,
      suggestion    VARCHAR2(1000 CHAR),
      status        VARCHAR2(20 CHAR) DEFAULT ''OPEN'' NOT NULL,
      create_time   TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_ai_consult_session PRIMARY KEY (id),
      CONSTRAINT uq_ai_session_no UNIQUE (session_no),
      CONSTRAINT ck_ai_consult_status CHECK (status IN (''OPEN'', ''CLOSED''))
    )';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'AI_PREDICTION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE ai_prediction (
      id            NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      pred_no       VARCHAR2(32 CHAR) NOT NULL,
      pred_type     VARCHAR2(30 CHAR) NOT NULL,
      score         NUMBER(10,4),
      detail        CLOB,
      create_time   TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_ai_prediction PRIMARY KEY (id),
      CONSTRAINT uq_ai_pred_no UNIQUE (pred_no)
    )';
  END IF;
END;
/

CREATE INDEX idx_ai_pred_type ON ai_prediction (pred_type);
