-- =============================================================
-- clinic_db V10：门诊流程补强（迭代9 A1~A8 / J3）
-- 说明：
--   1. checkin 增加分诊字段：priority（0=急诊 1=优先 2=普通）、
--      return_flag（回诊标记）、triage_nurse_id / triage_time（分诊操作留痕）
--   2. slot 增加 channel_type（NORMAL 普通号源 / GREEN 绿色通道号源：
--      老年/军人/急诊优先）与 overbook（该号源是否允许加号超挂）
--   3. schedule 增加 fee_type（NORMAL 普通 / EXPERT 专家号分层定价）
--      与 overbook（排班维度加号开关）
--   4. appointment 增加 overbook_flag（加号预约标记）
--   5. 新表 icd_dict：ICD-10 诊断字典（J3 病历诊断编码校验）
--   6. 新表 schedule_generate_log：自动排班 Job 执行日志（A8）
--   幂等说明：Oracle 无 ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS，
--   全部结构变更收敛进 PL/SQL 块按 user_tables/user_tab_columns/user_indexes
--   探测后再 EXECUTE IMMEDIATE，可安全重复执行（Flyway 重跑 / 手工补跑均无害）。
-- =============================================================

-- ==================== 1. checkin 分诊字段（A1/A6） ====================
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'CHECKIN' AND column_name = 'PRIORITY';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE checkin ADD (priority NUMBER(3) DEFAULT 2 NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'CHECKIN' AND column_name = 'RETURN_FLAG';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE checkin ADD (return_flag NUMBER(3) DEFAULT 0 NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'CHECKIN' AND column_name = 'TRIAGE_NURSE_ID';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE checkin ADD (triage_nurse_id NUMBER(19) DEFAULT NULL)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'CHECKIN' AND column_name = 'TRIAGE_TIME';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE checkin ADD (triage_time TIMESTAMP DEFAULT NULL)'; END IF;
END;
/
COMMENT ON COLUMN checkin.priority IS '分诊优先级: 0-急诊 / 1-优先 / 2-普通（默认普通）';
COMMENT ON COLUMN checkin.return_flag IS '回诊标记: 0-初诊排队 / 1-检查检验完成回诊（同档优先插队）';
COMMENT ON COLUMN checkin.triage_nurse_id IS '分诊操作护士用户ID（auth sys_user.id）';
COMMENT ON COLUMN checkin.triage_time IS '分诊操作时间';

-- ==================== 2. slot 绿色通道 + 加号开关（A2/A4） ====================
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'SLOT' AND column_name = 'CHANNEL_TYPE';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slot ADD (channel_type VARCHAR2(20 CHAR) DEFAULT ''NORMAL'' NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'SLOT' AND column_name = 'OVERBOOK';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE slot ADD (overbook NUMBER(3) DEFAULT 0 NOT NULL)'; END IF;
END;
/
COMMENT ON COLUMN slot.channel_type IS '号源通道: NORMAL-普通 / GREEN-绿色通道（老年/军人/急诊优先号源）';
COMMENT ON COLUMN slot.overbook IS '号源维度加号开关: 0-禁止 / 1-允许（加号时号源保持 BOOKED 不扣减）';

-- ==================== 3. schedule 分层定价 + 加号开关（A2/A5） ====================
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'SCHEDULE' AND column_name = 'FEE_TYPE';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE schedule ADD (fee_type VARCHAR2(20 CHAR) DEFAULT ''NORMAL'' NOT NULL)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'SCHEDULE' AND column_name = 'OVERBOOK';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE schedule ADD (overbook NUMBER(3) DEFAULT 0 NOT NULL)'; END IF;
END;
/
COMMENT ON COLUMN schedule.fee_type IS '号别: NORMAL-普通号（按 register_fee 收费）/ EXPERT-专家号（按医生职称档位价收费）';
COMMENT ON COLUMN schedule.overbook IS '排班维度加号开关: 0-禁止加号 / 1-允许加号超挂';

-- ==================== 4. appointment 加号标记（A2） ====================
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns WHERE table_name = 'APPOINTMENT' AND column_name = 'OVERBOOK_FLAG';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE appointment ADD (overbook_flag NUMBER(3) DEFAULT 0 NOT NULL)'; END IF;
END;
/
COMMENT ON COLUMN appointment.overbook_flag IS '加号预约标记: 0-正常预约 / 1-医生加号（就诊顺序排在正常预约之后）';

-- ==================== 5. icd_dict ICD-10 诊断字典（J3） ====================
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'ICD_DICT';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE icd_dict (
        id          NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
        icd_code    VARCHAR2(20 CHAR)   NOT NULL,
        icd_name    VARCHAR2(200 CHAR)  NOT NULL,
        category    VARCHAR2(50 CHAR)   DEFAULT NULL,
        is_common   NUMBER(3)           DEFAULT 0,
        status      NUMBER(3)           DEFAULT 1,
        create_time TIMESTAMP           DEFAULT SYSDATE NOT NULL,
        CONSTRAINT pk_icd_dict PRIMARY KEY (id),
        CONSTRAINT uk_icd_dict_code UNIQUE (icd_code)
    )'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_ICD_DICT_NAME';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_icd_dict_name ON icd_dict (icd_name)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_ICD_DICT_CATEGORY';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_icd_dict_category ON icd_dict (category)'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_ICD_DICT_COMMON';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_icd_dict_common ON icd_dict (is_common)'; END IF;
END;
/
COMMENT ON TABLE icd_dict IS 'ICD-10 诊断字典（病历诊断编码校验依据）';
COMMENT ON COLUMN icd_dict.icd_code IS 'ICD-10 编码（唯一，如 I10.x05 / E11）';
COMMENT ON COLUMN icd_dict.icd_name IS '诊断标准名称（中文规范名）';
COMMENT ON COLUMN icd_dict.category IS 'ICD 章节分类（如 循环系统/呼吸系统）';
COMMENT ON COLUMN icd_dict.is_common IS '常用标记: 0-普通 / 1-常用（录入联想优先展示）';
COMMENT ON COLUMN icd_dict.status IS '状态: 1-启用 / 0-停用';

-- 常用 ICD-10 种子数据（30 条，编码与需求清单逐字一致；Oracle 19c 不支持多行 VALUES，拆单条；幂等：重复执行安全）
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'I10',     '高血压',             '循环系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'I10');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'E11',     '2型糖尿病',          '内分泌、营养和代谢疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'E11');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'J06',     '急性上呼吸道感染',   '呼吸系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'J06');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'J03.9',   '急性扁桃体炎',       '呼吸系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'J03.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'K29',     '胃炎',               '消化系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'K29');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'A09',     '腹泻',               '传染病和寄生虫病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'A09');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'M54.5',   '腰痛',               '肌肉骨骼系统和结缔组织疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'M54.5');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'H10',     '结膜炎',             '眼和附器疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'H10');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'B34.9',   '病毒感染',           '传染病和寄生虫病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'B34.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'R50.9',   '发热',               '症状、体征和临床与实验室异常所见', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'R50.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'J20',     '急性支气管炎',       '呼吸系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'J20');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'I63',     '脑梗死',             '循环系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'I63');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'N39.0',   '尿路感染',           '泌尿生殖系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'N39.0');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'K35',     '急性阑尾炎',         '消化系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'K35');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'E78.5',   '高脂血症',           '内分泌、营养和代谢疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'E78.5');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'Z00.0',   '常规体检',           '影响健康状态与保健机构接触的因素', 0 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'Z00.0');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'J45',     '哮喘',               '呼吸系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'J45');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'I20',     '心绞痛',             '循环系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'I20');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'K76.807', '脂肪肝',             '消化系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'K76.807');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'G43.9',   '偏头痛',             '神经系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'G43.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'M17',     '膝骨关节病',         '肌肉骨骼系统和结缔组织疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'M17');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'L50.9',   '荨麻疹',             '皮肤和皮下组织疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'L50.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'D64.9',   '贫血',               '血液及造血器官疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'D64.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'E04',     '甲状腺结节',         '内分泌、营养和代谢疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'E04');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'J40',     '支气管炎待查',       '呼吸系统疾病', 0 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'J40');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'K59.907', '肠功能紊乱',         '消化系统疾病', 0 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'K59.907');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'N20',     '肾结石',             '泌尿生殖系统疾病', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'N20');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'R05.9',   '咳嗽',               '症状、体征和临床与实验室异常所见', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'R05.9');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'R51',     '头痛',               '症状、体征和临床与实验室异常所见', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'R51');
INSERT INTO icd_dict (icd_code, icd_name, category, is_common) SELECT 'R10.4',   '其他腹痛',           '症状、体征和临床与实验室异常所见', 1 FROM dual WHERE NOT EXISTS (SELECT 1 FROM icd_dict WHERE icd_code = 'R10.4');

-- ==================== 6. schedule_generate_log 自动排班 Job 日志（A8） ====================
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'SCHEDULE_GENERATE_LOG';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'CREATE TABLE schedule_generate_log (
        id            NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
        biz_date      DATE                NOT NULL,
        created_count NUMBER(10)          DEFAULT 0,
        message       VARCHAR2(500 CHAR)  DEFAULT NULL,
        create_time   TIMESTAMP           DEFAULT SYSDATE NOT NULL,
        CONSTRAINT pk_schedule_generate_log PRIMARY KEY (id)
    )'; END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_SGL_BIZ_DATE';
    IF v_cnt = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX idx_sgl_biz_date ON schedule_generate_log (biz_date)'; END IF;
END;
/
COMMENT ON TABLE schedule_generate_log IS '自动排班 Job 执行日志（每日凌晨自动生成未来第 7 天排班）';
COMMENT ON COLUMN schedule_generate_log.biz_date IS '本次生成目标出诊日期';
COMMENT ON COLUMN schedule_generate_log.created_count IS '本次实际新建排班数量';
COMMENT ON COLUMN schedule_generate_log.message IS '执行结果说明（跳过数量、失败原因等）';
