-- ============================================================
-- clinic_db V11：互联网医院与患者服务（迭代13 L3/K3/K1）
--   1. notice          院内公告/通知（L3）
--   2. evaluation      就诊满意度评价（K3，一次就诊一评）
--   3. online_consult  线上图文复诊单（K1）
--   4. online_consult_message  复诊图文消息（K1）
-- 幂等：user_tables 探测后创建
-- ============================================================

-- 1. 公告表（L3）
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'NOTICE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE notice (
            id             NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
            title          VARCHAR2(200 CHAR) NOT NULL,
            content        CLOB,
            notice_type    VARCHAR2(20 CHAR)  DEFAULT ''NOTICE'' NOT NULL,
            status         VARCHAR2(20 CHAR)  DEFAULT ''PUBLISHED'' NOT NULL,
            publisher_id   NUMBER(19)         DEFAULT NULL,
            publisher_name VARCHAR2(50 CHAR)  DEFAULT NULL,
            publish_time   TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            create_time    TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            update_time    TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_notice PRIMARY KEY (id)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_notice_status ON notice (status)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_notice_type ON notice (notice_type)';
    END IF;
END;
/
COMMENT ON TABLE notice IS '院内公告（L3）: notice_type=NOTICE通知/POLICY政策/ACTIVITY活动; status=PUBLISHED已发布/OFFLINE已下线';

-- 2. 满意度评价表（K3）
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'EVALUATION';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE evaluation (
            id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
            appointment_id  NUMBER(19)         NOT NULL,
            patient_id      NUMBER(19)         NOT NULL,
            doctor_id       NUMBER(19)         NOT NULL,
            department_id   NUMBER(19)         DEFAULT NULL,
            score           NUMBER(3)          NOT NULL,
            content         VARCHAR2(500 CHAR) DEFAULT NULL,
            create_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_evaluation PRIMARY KEY (id),
            CONSTRAINT uk_evaluation_appointment UNIQUE (appointment_id),
            CONSTRAINT ck_evaluation_score CHECK (score BETWEEN 1 AND 5)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_evaluation_doctor ON evaluation (doctor_id)';
    END IF;
END;
/
COMMENT ON TABLE evaluation IS '就诊满意度评价（K3）: score 1~5 星; 一次就诊一评（uk appointment_id）';

-- 3. 图文复诊单（K1）
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'ONLINE_CONSULT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE online_consult (
            id                NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
            consult_no        VARCHAR2(32 CHAR)   NOT NULL,
            patient_id        NUMBER(19)          NOT NULL,
            patient_name      VARCHAR2(50 CHAR)   DEFAULT NULL,
            doctor_id         NUMBER(19)          NOT NULL,
            medical_record_id NUMBER(19)          DEFAULT NULL,
            chief_complaint   VARCHAR2(1000 CHAR) NOT NULL,
            status            VARCHAR2(20 CHAR)   DEFAULT ''WAITING'' NOT NULL,
            prescription_id   NUMBER(19)          DEFAULT NULL,
            prescription_no   VARCHAR2(32 CHAR)   DEFAULT NULL,
            create_time       TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            accept_time       TIMESTAMP           DEFAULT NULL,
            close_time        TIMESTAMP           DEFAULT NULL,
            CONSTRAINT pk_online_consult PRIMARY KEY (id),
            CONSTRAINT uk_online_consult_no UNIQUE (consult_no)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_oc_patient ON online_consult (patient_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_oc_doctor ON online_consult (doctor_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_oc_status ON online_consult (status)';
    END IF;
END;
/
COMMENT ON TABLE online_consult IS '线上图文复诊（K1）: status=WAITING待接诊/IN_PROGRESS问诊中/CLOSED已结束; 续方回写 prescription_id/no';

-- 4. 复诊消息表（K1）
DECLARE v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'ONLINE_CONSULT_MESSAGE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE online_consult_message (
            id          NUMBER(19)           GENERATED BY DEFAULT AS IDENTITY,
            consult_id  NUMBER(19)           NOT NULL,
            sender_type VARCHAR2(10 CHAR)    NOT NULL,
            sender_id   NUMBER(19)           DEFAULT NULL,
            sender_name VARCHAR2(50 CHAR)    DEFAULT NULL,
            content     VARCHAR2(2000 CHAR)  NOT NULL,
            create_time TIMESTAMP            DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_oc_message PRIMARY KEY (id)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_ocm_consult ON online_consult_message (consult_id)';
    END IF;
END;
/
COMMENT ON TABLE online_consult_message IS '复诊图文消息（K1）: sender_type=PATIENT患者/DOCTOR医生';
