-- =====================================================================
-- V12: 迭代14 G1 急诊预检分级 + G2 抢救记录 + L4 考勤打卡（clinic）
-- 幂等：user_tables 探测后建表
-- =====================================================================

-- G1 急诊分诊记录（预检分级）
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'TRIAGE_RECORD';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE triage_record (
      id              NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      visit_no        VARCHAR2(32 CHAR) NOT NULL,
      patient_id      NUMBER(19)       NOT NULL,
      patient_name    VARCHAR2(50 CHAR) NOT NULL,
      triage_level    VARCHAR2(10 CHAR) NOT NULL,
      chief_complaint VARCHAR2(500 CHAR),
      temperature     NUMBER(4,1),
      pulse           NUMBER(10),
      blood_pressure  VARCHAR2(20 CHAR),
      department_id   NUMBER(19),
      doctor_id       NUMBER(19),
      status          VARCHAR2(20 CHAR) DEFAULT ''WAITING'' NOT NULL,
      triage_by       NUMBER(19),
      create_time     TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      update_time     TIMESTAMP,
      CONSTRAINT pk_triage_record PRIMARY KEY (id),
      CONSTRAINT uq_triage_visit_no UNIQUE (visit_no),
      CONSTRAINT ck_triage_level CHECK (triage_level IN (''RED'', ''ORANGE'', ''YELLOW'', ''GREEN'')),
      CONSTRAINT ck_triage_status CHECK (status IN (''WAITING'', ''TREATING'', ''DONE''))
    )';
  END IF;
END;
/

CREATE INDEX idx_triage_patient ON triage_record (patient_id);
CREATE INDEX idx_triage_level ON triage_record (triage_level);

-- G2 抢救记录
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'rescue_record';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE rescue_record (
      id              NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      rescue_no       VARCHAR2(32 CHAR) NOT NULL,
      patient_id      NUMBER(19)       NOT NULL,
      patient_name    VARCHAR2(50 CHAR) NOT NULL,
      triage_id       NUMBER(19),
      measures        CLOB,
      participants    VARCHAR2(200 CHAR),
      outcome         VARCHAR2(20 CHAR) DEFAULT ''ONGOING'' NOT NULL,
      start_time      TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      end_time        TIMESTAMP,
      create_time     TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_rescue_record PRIMARY KEY (id),
      CONSTRAINT uq_rescue_no UNIQUE (rescue_no),
      CONSTRAINT ck_rescue_outcome CHECK (outcome IN (''ONGOING'', ''SUCCESS'', ''DEATH''))
    )';
  END IF;
END;
/

CREATE INDEX idx_rescue_patient ON rescue_record (patient_id);

-- L4 考勤打卡（一人一天一条）
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'attendance';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE attendance (
      id              NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      user_id         NUMBER(19)       NOT NULL,
      user_name       VARCHAR2(50 CHAR) NOT NULL,
      work_date       DATE             NOT NULL,
      checkin_time    TIMESTAMP,
      checkout_time   TIMESTAMP,
      status          VARCHAR2(20 CHAR) DEFAULT ''ON_DUTY'' NOT NULL,
      remark          VARCHAR2(200 CHAR),
      create_time     TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_attendance PRIMARY KEY (id),
      CONSTRAINT uq_attendance_user_date UNIQUE (user_id, work_date),
      CONSTRAINT ck_attendance_status CHECK (status IN (''ON_DUTY'', ''OFF_DUTY''))
    )';
  END IF;
END;
/

CREATE INDEX idx_attendance_date ON attendance (work_date);
