-- =====================================================================
-- V13: 迭代15 B1 算法层（clinic：遗传排班建议 / 停诊重调度批次）
-- 幂等：user_tables 探测后建表
-- =====================================================================

-- GA 排班建议（周维度）
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'SCHEDULE_SUGGESTION';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE schedule_suggestion (
      id            NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      batch_no      VARCHAR2(32 CHAR) NOT NULL,
      week_start    DATE             NOT NULL,
      department_id NUMBER(19),
      doctor_id     NUMBER(19)       NOT NULL,
      doctor_name   VARCHAR2(50 CHAR),
      plan_days     VARCHAR2(7 CHAR) NOT NULL,
      fitness       NUMBER(8,4),
      status        VARCHAR2(20 CHAR) DEFAULT ''DRAFT'' NOT NULL,
      create_time   TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_schedule_suggestion PRIMARY KEY (id),
      CONSTRAINT ck_schedule_sugg_status CHECK (status IN (''DRAFT'', ''APPLIED'', ''REJECTED''))
    )';
  END IF;
END;
/

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_SSCHEDULE_WEEK';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_sschedule_week ON schedule_suggestion (week_start)';
  END IF;
END;
/

-- 停诊重调度批次
DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'RESCHEDULE_BATCH';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE reschedule_batch (
      id            NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      batch_no      VARCHAR2(32 CHAR) NOT NULL,
      doctor_id     NUMBER(19)       NOT NULL,
      stop_date     DATE             NOT NULL,
      affected_cnt  NUMBER(10)       DEFAULT 0 NOT NULL,
      suggestions   CLOB,
      status        VARCHAR2(20 CHAR) DEFAULT ''GENERATED'' NOT NULL,
      create_time   TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_reschedule_batch PRIMARY KEY (id),
      CONSTRAINT uq_reschedule_batch UNIQUE (batch_no),
      CONSTRAINT ck_resched_batch_status CHECK (status IN (''GENERATED'', ''NOTIFIED''))
    )';
  END IF;
END;
/
