-- ============================================================
-- clinic_db V1__init.sql（Oracle 19c 版，迭代6.5 MySQL→Oracle 迁移）
-- 核心诊疗服务：10 张表 + 初始数据（14 个科室）
-- 迁移规则见 docs/技术专项方案-组件离线化与Oracle迁移.md §5.3
-- 注：MySQL TIME 列 → TIMESTAMP（ojdbc set/getTime 兼容）；
--     MySQL DATE 列 → DATE（LocalDate 无损，时间部分为 00:00:00）
-- ============================================================

-- ==================== 1. department（科室表） ====================
CREATE TABLE department (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    dept_name    VARCHAR2(100 CHAR) NOT NULL,
    dept_code    VARCHAR2(50 CHAR)  NOT NULL,
    description  VARCHAR2(500 CHAR) DEFAULT NULL,
    location     VARCHAR2(100 CHAR) DEFAULT NULL,
    phone        VARCHAR2(20 CHAR)  DEFAULT NULL,
    status       NUMBER(3)          DEFAULT 1,
    sort_order   NUMBER(10)         DEFAULT 0,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id),
    CONSTRAINT uk_dept_code UNIQUE (dept_code)
);
CREATE INDEX idx_dept_status ON department (status);
COMMENT ON TABLE department IS '科室表';

-- ==================== 2. doctor（医生表） ====================
CREATE TABLE doctor (
    id            NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    user_id       NUMBER(19)         DEFAULT NULL,
    name          VARCHAR2(50 CHAR)  NOT NULL,
    gender        NUMBER(3)          DEFAULT 0,
    phone         VARCHAR2(20 CHAR)  DEFAULT NULL,
    department_id NUMBER(19)         NOT NULL,
    title         VARCHAR2(50 CHAR)  NOT NULL,
    specialty     VARCHAR2(255 CHAR) DEFAULT NULL,
    introduction  CLOB,
    status        NUMBER(3)          DEFAULT 1,
    create_time   TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time   TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_doctor PRIMARY KEY (id)
);
CREATE INDEX idx_doctor_department ON doctor (department_id);
CREATE INDEX idx_doctor_user_id ON doctor (user_id);
CREATE INDEX idx_doctor_status ON doctor (status);
COMMENT ON TABLE doctor IS '医生表';

-- ==================== 3. schedule（排班计划表） ====================
CREATE TABLE schedule (
    id            NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY,
    doctor_id     NUMBER(19)      NOT NULL,
    department_id NUMBER(19)      NOT NULL,
    schedule_date DATE            NOT NULL,
    period        VARCHAR2(10 CHAR) NOT NULL,
    period_start  TIMESTAMP       NOT NULL,
    period_end    TIMESTAMP       NOT NULL,
    total_slots   NUMBER(10)      NOT NULL,
    slot_duration NUMBER(10)      DEFAULT 10,
    register_fee  NUMBER(10,2)    DEFAULT 0.00,
    status        NUMBER(3)       DEFAULT 1,
    create_time   TIMESTAMP       DEFAULT SYSDATE NOT NULL,
    update_time   TIMESTAMP       DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_schedule PRIMARY KEY (id),
    CONSTRAINT uk_schedule UNIQUE (doctor_id, schedule_date, period)
);
CREATE INDEX idx_schedule_dept_date ON schedule (department_id, schedule_date);
CREATE INDEX idx_schedule_status ON schedule (status);
COMMENT ON TABLE schedule IS '排班计划表';

-- ==================== 4. slot（号源表） ====================
CREATE TABLE slot (
    id          NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    schedule_id NUMBER(19)         NOT NULL,
    slot_seq    NUMBER(10)         NOT NULL,
    slot_start  TIMESTAMP          NOT NULL,
    slot_end    TIMESTAMP          NOT NULL,
    status      VARCHAR2(20 CHAR)  DEFAULT 'AVAILABLE' NOT NULL,
    version     NUMBER(10)         DEFAULT 0,
    create_time TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_slot PRIMARY KEY (id),
    CONSTRAINT uk_slot_schedule_seq UNIQUE (schedule_id, slot_seq)
);
CREATE INDEX idx_slot_status ON slot (status);
COMMENT ON TABLE slot IS '号源表';

-- ==================== 5. appointment（预约订单表） ====================
CREATE TABLE appointment (
    id               NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    appointment_no   VARCHAR2(32 CHAR) NOT NULL,
    patient_id       NUMBER(19)        NOT NULL,
    slot_id          NUMBER(19)        NOT NULL,
    schedule_id      NUMBER(19)        NOT NULL,
    doctor_id        NUMBER(19)        NOT NULL,
    department_id    NUMBER(19)        NOT NULL,
    appointment_date DATE              NOT NULL,
    period           VARCHAR2(10 CHAR) NOT NULL,
    slot_seq         NUMBER(10)        NOT NULL,
    register_fee     NUMBER(10,2)      NOT NULL,
    order_status     VARCHAR2(20 CHAR) DEFAULT 'PENDING_PAY' NOT NULL,
    visit_status     VARCHAR2(20 CHAR) DEFAULT NULL,
    is_revisit       NUMBER(3)         DEFAULT 0,
    cancel_time      TIMESTAMP         DEFAULT NULL,
    cancel_reason    VARCHAR2(255 CHAR) DEFAULT NULL,
    create_time      TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    update_time      TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_appointment PRIMARY KEY (id),
    CONSTRAINT uk_appointment_no UNIQUE (appointment_no)
);
CREATE INDEX idx_appt_patient ON appointment (patient_id);
CREATE INDEX idx_appt_slot ON appointment (slot_id);
CREATE INDEX idx_appt_schedule ON appointment (schedule_id);
CREATE INDEX idx_appt_order_status ON appointment (order_status);
CREATE INDEX idx_appt_date_dept ON appointment (appointment_date, department_id);
CREATE INDEX idx_appt_doctor_date ON appointment (doctor_id, appointment_date);
COMMENT ON TABLE appointment IS '预约订单表';

-- ==================== 6. checkin（签到记录表） ====================
CREATE TABLE checkin (
    id             NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    appointment_id NUMBER(19)        NOT NULL,
    patient_id     NUMBER(19)        NOT NULL,
    department_id  NUMBER(19)        NOT NULL,
    doctor_id      NUMBER(19)        NOT NULL,
    checkin_time   TIMESTAMP         NOT NULL,
    queue_status   VARCHAR2(20 CHAR) DEFAULT 'WAITING' NOT NULL,
    call_time      TIMESTAMP         DEFAULT NULL,
    call_count     NUMBER(10)        DEFAULT 0,
    rejoin_time    TIMESTAMP         DEFAULT NULL,
    consult_room   VARCHAR2(50 CHAR) DEFAULT NULL,
    create_time    TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_checkin PRIMARY KEY (id),
    CONSTRAINT uk_checkin_appointment UNIQUE (appointment_id)
);
CREATE INDEX idx_checkin_dept_status ON checkin (department_id, queue_status);
CREATE INDEX idx_checkin_patient ON checkin (patient_id);
COMMENT ON TABLE checkin IS '签到记录表';

-- ==================== 7. medical_record（病历表） ====================
CREATE TABLE medical_record (
    id                NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    appointment_id    NUMBER(19)        NOT NULL,
    patient_id        NUMBER(19)        NOT NULL,
    doctor_id         NUMBER(19)        NOT NULL,
    department_id     NUMBER(19)        NOT NULL,
    chief_complaint   CLOB,
    present_illness   CLOB,
    past_history      CLOB,
    temperature       NUMBER(4,1)       DEFAULT NULL,
    pulse             NUMBER(10)        DEFAULT NULL,
    respiration       NUMBER(10)        DEFAULT NULL,
    blood_pressure    VARCHAR2(20 CHAR) DEFAULT NULL,
    diagnosis_code    VARCHAR2(20 CHAR) DEFAULT NULL,
    diagnosis_desc    VARCHAR2(500 CHAR) NOT NULL,
    treatment_opinion CLOB,
    referral_dept_id  NUMBER(19)        DEFAULT NULL,
    referral_reason   VARCHAR2(500 CHAR) DEFAULT NULL,
    status            VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    is_return_visit   NUMBER(3)         DEFAULT 0,
    create_time       TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_medical_record PRIMARY KEY (id)
);
CREATE INDEX idx_mr_appointment ON medical_record (appointment_id);
CREATE INDEX idx_mr_patient ON medical_record (patient_id);
CREATE INDEX idx_mr_doctor ON medical_record (doctor_id);
CREATE INDEX idx_mr_status ON medical_record (status);
COMMENT ON TABLE medical_record IS '病历表';

-- ==================== 8. prescription（处方主表） ====================
CREATE TABLE prescription (
    id                NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    prescription_no   VARCHAR2(32 CHAR) NOT NULL,
    medical_record_id NUMBER(19)        NOT NULL,
    patient_id        NUMBER(19)        NOT NULL,
    doctor_id         NUMBER(19)        NOT NULL,
    status            VARCHAR2(20 CHAR) DEFAULT 'PENDING_REVIEW' NOT NULL,
    review_comment    VARCHAR2(500 CHAR) DEFAULT NULL,
    create_time       TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_prescription PRIMARY KEY (id),
    CONSTRAINT uk_prescription_no UNIQUE (prescription_no)
);
CREATE INDEX idx_prescr_mr ON prescription (medical_record_id);
CREATE INDEX idx_prescr_patient ON prescription (patient_id);
CREATE INDEX idx_prescr_status ON prescription (status);
COMMENT ON TABLE prescription IS '处方主表';

-- ==================== 9. prescription_item（处方明细表） ====================
CREATE TABLE prescription_item (
    id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    prescription_id NUMBER(19)         NOT NULL,
    drug_id         NUMBER(19)         NOT NULL,
    drug_name       VARCHAR2(200 CHAR) NOT NULL,
    specification   VARCHAR2(100 CHAR) DEFAULT NULL,
    dosage          VARCHAR2(50 CHAR)  NOT NULL,
    usage_method    VARCHAR2(50 CHAR)  NOT NULL,
    frequency       VARCHAR2(50 CHAR)  NOT NULL,
    days            NUMBER(10)         NOT NULL,
    quantity        NUMBER(10)         NOT NULL,
    unit            VARCHAR2(20 CHAR)  NOT NULL,
    remark          VARCHAR2(500 CHAR) DEFAULT NULL,
    CONSTRAINT pk_prescription_item PRIMARY KEY (id)
);
CREATE INDEX idx_prescr_item ON prescription_item (prescription_id);
COMMENT ON TABLE prescription_item IS '处方明细表';

-- ==================== 10. stop_application（停诊申请表） ====================
CREATE TABLE stop_application (
    id              NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    schedule_id     NUMBER(19)        NOT NULL,
    doctor_id       NUMBER(19)        NOT NULL,
    apply_reason    VARCHAR2(500 CHAR) NOT NULL,
    status          VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    approve_comment VARCHAR2(500 CHAR) DEFAULT NULL,
    approved_by     NUMBER(19)        DEFAULT NULL,
    approve_time    TIMESTAMP         DEFAULT NULL,
    affected_count  NUMBER(10)        DEFAULT 0,
    refund_total    NUMBER(10,2)      DEFAULT 0.00,
    create_time     TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    update_time     TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_stop_application PRIMARY KEY (id)
);
CREATE INDEX idx_stop_status ON stop_application (status);
CREATE INDEX idx_stop_doctor ON stop_application (doctor_id);
CREATE INDEX idx_stop_schedule ON stop_application (schedule_id);
COMMENT ON TABLE stop_application IS '停诊申请表';

-- ==================== 初始数据：14 个科室（19c 不支持多行 VALUES，拆单条） ====================
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('内科',     'INTERNAL_MEDICINE',     '内科疾病诊疗',             1);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('外科',     'SURGERY',               '外科疾病及手术诊疗',       2);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('儿科',     'PEDIATRICS',            '儿童疾病诊疗',             3);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('妇产科',   'OBSTETRICS_GYNECOLOGY', '妇产科疾病诊疗',           4);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('骨科',     'ORTHOPEDICS',           '骨骼、关节及运动系统疾病', 5);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('眼科',     'OPHTHALMOLOGY',         '眼部疾病诊疗',             6);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('耳鼻喉科', 'ENT',                   '耳鼻喉及头颈外科疾病',     7);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('皮肤科',   'DERMATOLOGY',           '皮肤疾病诊疗',             8);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('神经内科', 'NEUROLOGY',             '神经系统疾病诊疗',         9);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('心内科',   'CARDIOLOGY',            '心血管系统疾病诊疗',       10);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('呼吸内科', 'RESPIRATORY',           '呼吸系统疾病诊疗',         11);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('消化内科', 'GASTROENTEROLOGY',      '消化系统疾病诊疗',         12);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('内分泌科', 'ENDOCRINOLOGY',         '内分泌及代谢疾病诊疗',     13);
INSERT INTO department (dept_name, dept_code, description, sort_order) VALUES ('口腔科',   'STOMATOLOGY',           '口腔及牙科疾病诊疗',       14);
