-- ============================================================
-- clinic_db V8：会诊 / 转诊 / 随访 / 医疗证明（Oracle 版，功能补全第一批）
-- 说明：
--   1. 会诊请求表 consultation_request：医生发起会诊 → 会诊医生处理 → 结论
--   2. 转诊单 referral_order：转出/转入科室、状态机、与病历 referral 字段打通
--   3. 随访计划 follow_up_plan + 随访记录 follow_up_record
--   4. 医疗证明 medical_certificate（诊断证明/病假条/转诊单/医疗建议）
--   幂等：全部 INSERT ... SELECT + NOT EXISTS；IF NOT EXISTS 由 Flyway 单次执行语义替代
-- ============================================================

-- 1. 会诊请求
CREATE TABLE consultation_request (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    request_no        VARCHAR2(32 CHAR)  NOT NULL,
    medical_record_id NUMBER(19)         NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    apply_dept_id     NUMBER(19)         NOT NULL,
    apply_doctor_id   NUMBER(19)         NOT NULL,
    target_dept_id    NUMBER(19)         NOT NULL,
    target_doctor_id  NUMBER(19)         DEFAULT NULL,
    reason            VARCHAR2(1000 CHAR) DEFAULT NULL,
    status            VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    consult_opinion   CLOB,
    consult_doctor_id NUMBER(19)         DEFAULT NULL,
    consult_time      TIMESTAMP          DEFAULT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_consultation_request PRIMARY KEY (id),
    CONSTRAINT uk_consult_request_no UNIQUE (request_no)
);
CREATE INDEX idx_consult_req_target ON consultation_request (target_dept_id, status);
CREATE INDEX idx_consult_req_patient ON consultation_request (patient_id);
COMMENT ON TABLE consultation_request IS '会诊请求表';

-- 2. 转诊单
CREATE TABLE referral_order (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    referral_no       VARCHAR2(32 CHAR)  NOT NULL,
    medical_record_id NUMBER(19)         NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    from_dept_id      NUMBER(19)         NOT NULL,
    from_doctor_id    NUMBER(19)         NOT NULL,
    to_dept_id        NUMBER(19)         NOT NULL,
    reason            VARCHAR2(1000 CHAR) DEFAULT NULL,
    status            VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    accept_time       TIMESTAMP          DEFAULT NULL,
    complete_time     TIMESTAMP          DEFAULT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_referral_order PRIMARY KEY (id),
    CONSTRAINT uk_referral_no UNIQUE (referral_no)
);
CREATE INDEX idx_referral_to_dept ON referral_order (to_dept_id, status);
CREATE INDEX idx_referral_patient ON referral_order (patient_id);
COMMENT ON TABLE referral_order IS '转诊单表';

-- 3. 随访计划
CREATE TABLE follow_up_plan (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    patient_id        NUMBER(19)         NOT NULL,
    medical_record_id NUMBER(19)         DEFAULT NULL,
    doctor_id         NUMBER(19)         NOT NULL,
    follow_date       DATE               NOT NULL,
    follow_method     VARCHAR2(50 CHAR)  NOT NULL,
    template          VARCHAR2(500 CHAR) DEFAULT NULL,
    status            VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_follow_up_plan PRIMARY KEY (id)
);
CREATE INDEX idx_followup_patient ON follow_up_plan (patient_id);
CREATE INDEX idx_followup_doctor ON follow_up_plan (doctor_id);
CREATE INDEX idx_followup_date ON follow_up_plan (follow_date);
COMMENT ON TABLE follow_up_plan IS '随访计划表';

-- 4. 随访记录
CREATE TABLE follow_up_record (
    id               NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    plan_id          NUMBER(19)          NOT NULL,
    patient_id       NUMBER(19)          NOT NULL,
    doctor_id        NUMBER(19)          NOT NULL,
    content          VARCHAR2(2000 CHAR) DEFAULT NULL,
    next_follow_date DATE                DEFAULT NULL,
    create_time      TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_follow_up_record PRIMARY KEY (id)
);
CREATE INDEX idx_followup_record_plan ON follow_up_record (plan_id);
COMMENT ON TABLE follow_up_record IS '随访记录表';

-- 5. 医疗证明
CREATE TABLE medical_certificate (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    cert_no           VARCHAR2(32 CHAR)  NOT NULL,
    cert_type         VARCHAR2(30 CHAR)  NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    doctor_id         NUMBER(19)         NOT NULL,
    medical_record_id NUMBER(19)         DEFAULT NULL,
    content           CLOB,
    days              NUMBER(10)         DEFAULT NULL,
    start_date        DATE               DEFAULT NULL,
    status            VARCHAR2(20 CHAR)  DEFAULT 'ISSUED' NOT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_medical_certificate PRIMARY KEY (id),
    CONSTRAINT uk_cert_no UNIQUE (cert_no)
);
CREATE INDEX idx_cert_patient ON medical_certificate (patient_id);
COMMENT ON TABLE medical_certificate IS '医疗证明表';
