-- ============================================================
-- payment_db V1__init.sql（Oracle 19c 版，迭代6.5 迁移）
-- 支付调度服务：4 张表
-- ============================================================

-- ==================== 1. payment_order（支付订单表） ====================
CREATE TABLE payment_order (
    id             NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    order_no       VARCHAR2(32 CHAR) NOT NULL,
    appointment_id NUMBER(19)        NOT NULL,
    patient_id     NUMBER(19)        NOT NULL,
    amount         NUMBER(10,2)      NOT NULL,
    order_type     VARCHAR2(20 CHAR) NOT NULL,
    status         VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    pay_time       TIMESTAMP         DEFAULT NULL,
    pay_method     VARCHAR2(20 CHAR) DEFAULT NULL,
    expire_time    TIMESTAMP         NOT NULL,
    cancel_time    TIMESTAMP         DEFAULT NULL,
    version        NUMBER(10)        DEFAULT 0,
    create_time    TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    update_time    TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_payment_order PRIMARY KEY (id),
    CONSTRAINT uk_payment_order_no UNIQUE (order_no)
);
CREATE INDEX idx_pay_appointment ON payment_order (appointment_id);
CREATE INDEX idx_pay_patient ON payment_order (patient_id);
CREATE INDEX idx_pay_status ON payment_order (status);
CREATE INDEX idx_pay_expire_time ON payment_order (expire_time);
COMMENT ON TABLE payment_order IS '支付订单表';

-- ==================== 2. local_message（本地消息表） ====================
CREATE TABLE local_message (
    id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    message_id      VARCHAR2(64 CHAR)  NOT NULL,
    exchange        VARCHAR2(100 CHAR) NOT NULL,
    routing_key     VARCHAR2(100 CHAR) NOT NULL,
    message_body    CLOB               NOT NULL,
    status          VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    retry_count     NUMBER(10)         DEFAULT 0,
    max_retry       NUMBER(10)         DEFAULT 3,
    next_retry_time TIMESTAMP          DEFAULT NULL,
    fail_reason     VARCHAR2(500 CHAR) DEFAULT NULL,
    business_type   VARCHAR2(50 CHAR)  NOT NULL,
    business_id     VARCHAR2(64 CHAR)  NOT NULL,
    create_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_local_message PRIMARY KEY (id),
    CONSTRAINT uk_local_msg_id UNIQUE (message_id)
);
CREATE INDEX idx_msg_status ON local_message (status);
CREATE INDEX idx_msg_business ON local_message (business_id);
COMMENT ON TABLE local_message IS '本地消息表';

-- ==================== 3. refund_record（退款记录表） ====================
CREATE TABLE refund_record (
    id               NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    refund_no        VARCHAR2(32 CHAR)  NOT NULL,
    payment_order_id NUMBER(19)         NOT NULL,
    appointment_id   NUMBER(19)         NOT NULL,
    refund_amount    NUMBER(10,2)       NOT NULL,
    refund_reason    VARCHAR2(255 CHAR) NOT NULL,
    refund_type      VARCHAR2(30 CHAR)  NOT NULL,
    status           VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    create_time      TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_refund_record PRIMARY KEY (id),
    CONSTRAINT uk_refund_no UNIQUE (refund_no)
);
CREATE INDEX idx_refund_order ON refund_record (payment_order_id);
CREATE INDEX idx_refund_appointment ON refund_record (appointment_id);
COMMENT ON TABLE refund_record IS '退款记录表';

-- ==================== 4. notification（站内信通知表） ====================
CREATE TABLE notification (
    id          NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    patient_id  NUMBER(19)         NOT NULL,
    title       VARCHAR2(200 CHAR) NOT NULL,
    content     CLOB               NOT NULL,
    notify_type VARCHAR2(30 CHAR)  NOT NULL,
    related_id  VARCHAR2(64 CHAR)  DEFAULT NULL,
    is_read     NUMBER(3)          DEFAULT 0,
    read_time   TIMESTAMP          DEFAULT NULL,
    create_time TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_notification PRIMARY KEY (id)
);
CREATE INDEX idx_notify_patient ON notification (patient_id);
CREATE INDEX idx_notify_is_read ON notification (is_read);
CREATE INDEX idx_notify_create_time ON notification (create_time);
COMMENT ON TABLE notification IS '站内信通知表';
