-- ============================================================
-- payment_db V6：收费员代缴费 + 诊疗费退费 + 日结对账（Oracle 19c 版）
-- 说明：对齐真实医院收费处业务
--   1. refund_record 的 appointment_id 改为可空（诊疗费退费不关联预约），新增 order_type
--   2. payment_order 新增 cashier_id（收费员代缴费记录）、settle_flag（日结标记）
--   3. 新增 settle_record（收费员日结单表）
-- ============================================================

-- 1. 退款记录：appointment_id 可空 + 新增 order_type
ALTER TABLE refund_record
    MODIFY (appointment_id NUMBER(19) DEFAULT NULL);
ALTER TABLE refund_record
    ADD (order_type VARCHAR2(20 CHAR) DEFAULT NULL);

-- 2. 支付订单：收费员代缴费记录 + 日结标记
ALTER TABLE payment_order
    ADD (cashier_id  NUMBER(19) DEFAULT NULL,
         settle_flag NUMBER(3)  DEFAULT 0 NOT NULL);

-- 3. 收费员日结单表（同一收费员 + 日期唯一，幂等）
CREATE TABLE settle_record (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    settle_no    VARCHAR2(32 CHAR)  NOT NULL,
    cashier_id   NUMBER(19)         NOT NULL,
    settle_date  DATE               NOT NULL,
    total_amount NUMBER(10,2)       NOT NULL,
    order_count  NUMBER(10)         NOT NULL,
    detail       CLOB,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_settle_record PRIMARY KEY (id),
    CONSTRAINT uk_settle_cashier_date UNIQUE (cashier_id, settle_date)
);
COMMENT ON TABLE settle_record IS '收费员日结单表';
