-- ============================================================
-- payment_db V9：医保结算与统一收费目录（迭代11 医保与财务 H1~H4）
-- 内容：
--   1. charge_item             统一收费项目目录（H4，供自费/医保结算共用）
--   2. charge_item_adjust_log  调价历史（调价与目录更新同事务落库）
--   3. insurance_catalog       医保目录映射（H1，甲/乙/自费三色分类）
--   4. insurance_settle        医保结算单（H2，MI+yyyyMMdd+6 位流水）
--   5. seq_settle_no           医保结算单流水序列
--   6. 预置 3 个示例收费项目（TREAT01/MAT01/SVC01，便于联调演示）
-- 结算规则说明：甲类统筹 80%、乙类先行自付 15% 后剩余按统筹 80%、自费 0%，
--   比例以常量写死于 InsuranceSettleService，detail_json 保留逐项计算过程。
-- 幂等：Oracle 无 IF NOT EXISTS，所有 CREATE TABLE / CREATE INDEX /
--       CREATE SEQUENCE 收敛进 PL/SQL 块，按 user_tables / user_tab_columns /
--       user_indexes / user_sequences 探测后 EXECUTE IMMEDIATE；
--       种子数据 INSERT ... SELECT + NOT EXISTS。
-- 注意：UNIQUE 约束会自动创建同列唯一索引，故 uk_charge_item_code（item_code）、
--       uk_ins_cat（item_type,item_ref_id）、uk_insurance_settle_no（settle_no）
--       三组列上不再另建普通索引（迭代 10 踩过 ORA-01408）。
-- ============================================================

DECLARE
    v_cnt NUMBER := 0;
BEGIN

    -- ==================== 0. 医保结算单流水序列 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'SEQ_SETTLE_NO';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_settle_no START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    -- ==================== 1. charge_item 统一收费项目目录（H4） ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'CHARGE_ITEM';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE charge_item (
            id           NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
            item_code    VARCHAR2(30 CHAR)   NOT NULL,
            item_name    VARCHAR2(100 CHAR)  NOT NULL,
            category     VARCHAR2(20 CHAR)   DEFAULT NULL,
            unit         VARCHAR2(20 CHAR)   DEFAULT NULL,
            unit_price   NUMBER(10,2)        NOT NULL,
            price_status VARCHAR2(20 CHAR)   DEFAULT ''ACTIVE'' NOT NULL,
            adjust_note  VARCHAR2(300 CHAR)  DEFAULT NULL,
            create_time  TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            update_time  TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_charge_item PRIMARY KEY (id),
            CONSTRAINT uk_charge_item_code UNIQUE (item_code)
        )';
    END IF;
    -- 兜底补列（表已存在但缺列，如手工建库/部分回滚）
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
     WHERE table_name = 'CHARGE_ITEM' AND column_name = 'ADJUST_NOTE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE charge_item ADD (adjust_note VARCHAR2(300 CHAR) DEFAULT NULL)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_CHARGE_ITEM_CATEGORY';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_charge_item_category ON charge_item (category)';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE charge_item IS ''统一收费项目目录（诊疗/耗材/服务/检查/检验，category: DIAGNOSIS|MATERIAL|SERVICE|EXAM|LAB; price_status: ACTIVE|ADJUSTED|DEPRECATED）''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN charge_item.price_status IS ''价格状态: ACTIVE-启用 > ADJUSTED-已调价(保留调价痕迹) / DEPRECATED-停用''';

    -- ==================== 2. charge_item_adjust_log 调价历史 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'CHARGE_ITEM_ADJUST_LOG';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE charge_item_adjust_log (
            id          NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
            item_id     NUMBER(19)          NOT NULL,
            old_price   NUMBER(10,2)        DEFAULT NULL,
            new_price   NUMBER(10,2)        DEFAULT NULL,
            reason      VARCHAR2(300 CHAR)  DEFAULT NULL,
            operator_id NUMBER(19)          DEFAULT NULL,
            create_time TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_charge_item_adjust_log PRIMARY KEY (id)
        )';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_ADJUST_LOG_ITEM';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_adjust_log_item ON charge_item_adjust_log (item_id)';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE charge_item_adjust_log IS ''收费项目调价历史（调价动作与 charge_item 主表更新同事务写入）''';

    -- ==================== 3. insurance_catalog 医保目录映射（H1） ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'INSURANCE_CATALOG';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE insurance_catalog (
            id              NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
            item_type       VARCHAR2(20 CHAR)  NOT NULL,
            item_ref_id     NUMBER(19)         DEFAULT NULL,
            item_name       VARCHAR2(100 CHAR) DEFAULT NULL,
            catalog_class   VARCHAR2(10 CHAR)  NOT NULL,
            reimburse_ratio NUMBER(5,2)        DEFAULT 0 NOT NULL,
            status          NUMBER(3)          DEFAULT 1 NOT NULL,
            create_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            update_time     TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_insurance_catalog PRIMARY KEY (id),
            CONSTRAINT uk_ins_cat UNIQUE (item_type, item_ref_id)
        )';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE insurance_catalog IS ''医保目录映射（item_type: REGISTER|DRUG|EXAM|LAB|TREATMENT|MATERIAL|CHARGED_ITEM; catalog_class: A-甲类 B-乙类 C-自费）''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN insurance_catalog.reimburse_ratio IS ''比例(%): 甲类存 100.00、乙类存先行自付比例(默认 15.00)、自费存 0；仅供人工核对，结算算法以 Service 常量为准''';

    -- ==================== 4. insurance_settle 医保结算单（H2） ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'INSURANCE_SETTLE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE insurance_settle (
            id                   NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
            settle_no            VARCHAR2(30 CHAR) NOT NULL,
            patient_id           NUMBER(19)        NOT NULL,
            insurance_no         VARCHAR2(50 CHAR) DEFAULT NULL,
            biz_type             VARCHAR2(20 CHAR) DEFAULT NULL,
            biz_ref_id           NUMBER(19)        DEFAULT NULL,
            total_amount         NUMBER(10,2)      DEFAULT 0 NOT NULL,
            catalog_a_amount     NUMBER(10,2)      DEFAULT 0 NOT NULL,
            catalog_b_amount     NUMBER(10,2)      DEFAULT 0 NOT NULL,
            self_amount          NUMBER(10,2)      DEFAULT 0 NOT NULL,
            insurance_pay        NUMBER(10,2)      DEFAULT 0 NOT NULL,
            personal_account_pay NUMBER(10,2)      DEFAULT 0 NOT NULL,
            cash_amount          NUMBER(10,2)      DEFAULT 0 NOT NULL,
            detail_json          CLOB,
            status               VARCHAR2(20 CHAR) DEFAULT ''SETTLED'' NOT NULL,
            operator_id          NUMBER(19)        DEFAULT NULL,
            create_time          TIMESTAMP         DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_insurance_settle PRIMARY KEY (id),
            CONSTRAINT uk_insurance_settle_no UNIQUE (settle_no)
        )';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_INS_SETTLE_PATIENT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_ins_settle_patient ON insurance_settle (patient_id)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_INS_SETTLE_BIZ';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_ins_settle_biz ON insurance_settle (biz_type, biz_ref_id)';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE insurance_settle IS ''医保结算单（biz_type: REGISTER-挂号|OUTPATIENT-门诊|INPATIENT-住院; biz_ref_id 关联既有 payment_order/settle_record id，可空）''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN insurance_settle.status IS ''状态: SETTLED-已结算 > REVERSED-已冲正（轻量模拟，不回滚支付单）''';
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN insurance_settle.detail_json IS ''逐项拆分明细 JSON 数组（itemName/itemType/catalogClass/amount/insurancePay/personalPay/firstSelfPay/note，保留逐项计算过程）''';

END;
/

-- ==================== 6. 预置示例收费项目（幂等种子） ====================
INSERT INTO charge_item (item_code, item_name, category, unit, unit_price, price_status, create_time, update_time)
SELECT 'TREAT01', '普通诊查费', 'DIAGNOSIS', '次', 10.00, 'ACTIVE', SYSDATE, SYSDATE
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM charge_item WHERE item_code = 'TREAT01');

INSERT INTO charge_item (item_code, item_name, category, unit, unit_price, price_status, create_time, update_time)
SELECT 'MAT01', '一次性输液器', 'MATERIAL', '套', 2.50, 'ACTIVE', SYSDATE, SYSDATE
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM charge_item WHERE item_code = 'MAT01');

INSERT INTO charge_item (item_code, item_name, category, unit, unit_price, price_status, create_time, update_time)
SELECT 'SVC01', '诊疗服务费', 'SERVICE', '次', 15.00, 'ACTIVE', SYSDATE, SYSDATE
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM charge_item WHERE item_code = 'SVC01');
