-- ============================================================
-- inpatient_db V1__init.sql（Oracle 19c 版，迭代6.5 迁移）
-- 住院服务：入院/床位/占床/医嘱/执行/生命体征/预交金/出院
-- 时间戳留痕（供后续算法层/AI 素材）
-- ============================================================

-- 1. admission（入院登记主表）
CREATE TABLE admission (
    id                    NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    admission_no          VARCHAR2(32 CHAR)  NOT NULL,
    patient_id            NUMBER(19)         NOT NULL,
    department_id         NUMBER(19)         NOT NULL,
    attending_doctor_id   NUMBER(19)         NOT NULL,
    attending_doctor_name VARCHAR2(50 CHAR)  DEFAULT NULL,
    admission_diag        VARCHAR2(500 CHAR) NOT NULL,
    expected_days         NUMBER(10)         DEFAULT NULL,
    admission_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    status                VARCHAR2(20 CHAR)  DEFAULT 'ADMITTED' NOT NULL,
    create_time           TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time           TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_admission PRIMARY KEY (id),
    CONSTRAINT uk_admission_no UNIQUE (admission_no)
);
CREATE INDEX idx_admission_patient ON admission (patient_id);
CREATE INDEX idx_admission_dept ON admission (department_id);
CREATE INDEX idx_admission_status ON admission (status);
COMMENT ON TABLE admission IS '入院登记表';

-- 2. bed（床位字典）
CREATE TABLE bed (
    id            NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    department_id NUMBER(19)        NOT NULL,
    room_no       VARCHAR2(20 CHAR) NOT NULL,
    bed_no        VARCHAR2(20 CHAR) NOT NULL,
    bed_type      VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    daily_fee     NUMBER(10,2)      DEFAULT 0.00 NOT NULL,
    status        VARCHAR2(20 CHAR) DEFAULT 'AVAILABLE' NOT NULL,
    create_time   TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    update_time   TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_bed PRIMARY KEY (id),
    CONSTRAINT uk_bed_dept_room_no UNIQUE (department_id, room_no, bed_no)
);
CREATE INDEX idx_bed_dept ON bed (department_id);
CREATE INDEX idx_bed_status ON bed (status);
COMMENT ON TABLE bed IS '床位字典表';

-- 3. bed_occupancy（占床记录，含转床历史）
CREATE TABLE bed_occupancy (
    id          NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    admission_id NUMBER(19)       NOT NULL,
    bed_id      NUMBER(19)        NOT NULL,
    start_time  TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    end_time    TIMESTAMP         DEFAULT NULL,
    change_type VARCHAR2(20 CHAR) DEFAULT 'ADMIT' NOT NULL,
    create_time TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_bed_occupancy PRIMARY KEY (id)
);
CREATE INDEX idx_occupancy_admission ON bed_occupancy (admission_id);
CREATE INDEX idx_occupancy_bed ON bed_occupancy (bed_id);
COMMENT ON TABLE bed_occupancy IS '占床记录表';

-- 4. inpatient_medical_order（住院医嘱：长期/临时）
CREATE TABLE inpatient_medical_order (
    id               NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    order_no         VARCHAR2(32 CHAR)   NOT NULL,
    admission_id     NUMBER(19)          NOT NULL,
    doctor_id        NUMBER(19)          NOT NULL,
    order_type       VARCHAR2(20 CHAR)   DEFAULT 'TEMPORARY' NOT NULL,
    category         VARCHAR2(30 CHAR)   NOT NULL,
    content          VARCHAR2(1000 CHAR) NOT NULL,
    frequency        VARCHAR2(20 CHAR)   DEFAULT NULL,
    status           VARCHAR2(20 CHAR)   DEFAULT 'OPEN' NOT NULL,
    open_time        TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    confirm_time     TIMESTAMP           DEFAULT NULL,
    confirm_nurse_id NUMBER(19)          DEFAULT NULL,
    stop_time        TIMESTAMP           DEFAULT NULL,
    create_time      TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    update_time      TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_inpatient_medical_order PRIMARY KEY (id),
    CONSTRAINT uk_order_no UNIQUE (order_no)
);
CREATE INDEX idx_order_admission ON inpatient_medical_order (admission_id);
CREATE INDEX idx_order_status ON inpatient_medical_order (status);
COMMENT ON TABLE inpatient_medical_order IS '住院医嘱表';

-- 5. order_execution（医嘱执行记录：执行人/时间/结果）
CREATE TABLE order_execution (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    order_id     NUMBER(19)         NOT NULL,
    admission_id NUMBER(19)         NOT NULL,
    executor_id  NUMBER(19)         NOT NULL,
    execute_time TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    result       VARCHAR2(500 CHAR) DEFAULT NULL,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_order_execution PRIMARY KEY (id)
);
CREATE INDEX idx_exec_order ON order_execution (order_id);
CREATE INDEX idx_exec_admission ON order_execution (admission_id);
COMMENT ON TABLE order_execution IS '医嘱执行记录表';

-- 6. vital_sign（生命体征：多时段）
CREATE TABLE vital_sign (
    id             NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    admission_id   NUMBER(19)        NOT NULL,
    temperature    NUMBER(4,1)       DEFAULT NULL,
    pulse          NUMBER(10)        DEFAULT NULL,
    respiration    NUMBER(10)        DEFAULT NULL,
    blood_pressure VARCHAR2(20 CHAR) DEFAULT NULL,
    blood_oxygen   NUMBER(10)        DEFAULT NULL,
    record_time    TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    operator_id    NUMBER(19)        DEFAULT NULL,
    create_time    TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_vital_sign PRIMARY KEY (id)
);
CREATE INDEX idx_vital_admission_time ON vital_sign (admission_id, record_time);
COMMENT ON TABLE vital_sign IS '生命体征表';

-- 7. deposit（预交金流水）
CREATE TABLE deposit (
    id            NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    admission_id  NUMBER(19)   NOT NULL,
    amount        NUMBER(10,2) NOT NULL,
    pay_method    VARCHAR2(20 CHAR) DEFAULT 'CASH' NOT NULL,
    balance_after NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    operator_id   NUMBER(19)   DEFAULT NULL,
    create_time   TIMESTAMP    DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_deposit PRIMARY KEY (id)
);
CREATE INDEX idx_deposit_admission ON deposit (admission_id);
COMMENT ON TABLE deposit IS '预交金流水表';

-- 8. inpatient_fee（住院费用流水：床位/诊疗/药品/检查检验）
CREATE TABLE inpatient_fee (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    admission_id NUMBER(19)         NOT NULL,
    fee_type     VARCHAR2(20 CHAR)  NOT NULL,
    item_name    VARCHAR2(200 CHAR) NOT NULL,
    amount       NUMBER(10,2)       NOT NULL,
    bill_date    DATE               NOT NULL,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_inpatient_fee PRIMARY KEY (id)
);
CREATE INDEX idx_fee_admission_date ON inpatient_fee (admission_id, bill_date);
COMMENT ON TABLE inpatient_fee IS '住院费用流水表';

-- 9. discharge_summary（出院小结）
CREATE TABLE discharge_summary (
    id                   NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    admission_id         NUMBER(19)         NOT NULL,
    admission_diag       VARCHAR2(500 CHAR) NOT NULL,
    discharge_diag       VARCHAR2(500 CHAR) NOT NULL,
    treatment_process    CLOB,
    discharge_condition  VARCHAR2(500 CHAR) DEFAULT NULL,
    discharge_advice     CLOB,
    doctor_id            NUMBER(19)         NOT NULL,
    settlement_amount    NUMBER(10,2)       DEFAULT 0.00,
    deposit_balance      NUMBER(10,2)       DEFAULT 0.00,
    discharge_time       TIMESTAMP          DEFAULT NULL,
    create_time          TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time          TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_discharge_summary PRIMARY KEY (id),
    CONSTRAINT uk_discharge_admission UNIQUE (admission_id)
);
COMMENT ON TABLE discharge_summary IS '出院小结表';

-- 床位种子：14 个临床科室各 6 张（2 间病房），含 1 张 ICU
INSERT INTO bed (department_id, room_no, bed_no, bed_type, daily_fee)
SELECT d.dept_id, b.room_no, b.bed_no,
       CASE WHEN b.room_no = '201' AND b.bed_no = '1' THEN 'ICU' ELSE 'NORMAL' END,
       CASE WHEN b.room_no = '201' AND b.bed_no = '1' THEN 500.00 ELSE 80.00 END
FROM (
    SELECT 1 AS dept_id FROM dual UNION ALL SELECT 2 FROM dual UNION ALL SELECT 3 FROM dual UNION ALL SELECT 4 FROM dual UNION ALL
    SELECT 5 FROM dual UNION ALL SELECT 6 FROM dual UNION ALL SELECT 7 FROM dual UNION ALL SELECT 8 FROM dual UNION ALL
    SELECT 9 FROM dual UNION ALL SELECT 10 FROM dual UNION ALL SELECT 11 FROM dual UNION ALL SELECT 12 FROM dual UNION ALL
    SELECT 13 FROM dual UNION ALL SELECT 14 FROM dual
) d
CROSS JOIN (
    SELECT '101' AS room_no, '1' AS bed_no FROM dual UNION ALL
    SELECT '101','2' FROM dual UNION ALL SELECT '101','3' FROM dual UNION ALL
    SELECT '201','1' FROM dual UNION ALL SELECT '201','2' FROM dual UNION ALL SELECT '201','3' FROM dual
) b;
