-- ============================================================
-- inpatient_db V2__inpatient_extension.sql（Oracle 19c 版）
-- 住院扩展：护理病历(E2) / 院内会诊(E1) / 手术申请(E6) / 病案首页(E3)
-- IF NOT EXISTS 由 Flyway 单次执行语义替代
-- ============================================================

-- 1. nursing_record 护理病历（护理记录单/出入量）
CREATE TABLE nursing_record (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    admission_id NUMBER(19)         NOT NULL,
    record_type  VARCHAR2(20 CHAR)  DEFAULT 'ROUTINE' NOT NULL,
    content      CLOB,
    intake_ml    NUMBER(10)         DEFAULT NULL,
    output_ml    NUMBER(10)         DEFAULT NULL,
    nurse_id     NUMBER(19)         NOT NULL,
    record_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_nursing_record PRIMARY KEY (id)
);
CREATE INDEX idx_nursing_admission ON nursing_record (admission_id, record_time);
COMMENT ON TABLE nursing_record IS '护理病历表';

-- 2. inpatient_consult 住院院内会诊
CREATE TABLE inpatient_consult (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    admission_id      NUMBER(19)         NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    request_dept_id   NUMBER(19)         NOT NULL,
    request_doctor_id NUMBER(19)         NOT NULL,
    target_dept_id    NUMBER(19)         NOT NULL,
    target_doctor_id  NUMBER(19)         DEFAULT NULL,
    reason            VARCHAR2(500 CHAR) NOT NULL,
    opinion           CLOB,
    status            VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    handle_doctor_id  NUMBER(19)         DEFAULT NULL,
    handle_time       TIMESTAMP          DEFAULT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_inpatient_consult PRIMARY KEY (id)
);
CREATE INDEX idx_consult_admission ON inpatient_consult (admission_id);
CREATE INDEX idx_consult_target ON inpatient_consult (target_dept_id, status);
COMMENT ON TABLE inpatient_consult IS '住院院内会诊表';

-- 3. surgery_apply 手术申请（迭代6 建单，迭代10 排台执行）
CREATE TABLE surgery_apply (
    id              NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
    admission_id    NUMBER(19)          NOT NULL,
    patient_id      NUMBER(19)          NOT NULL,
    surgery_name    VARCHAR2(200 CHAR)  NOT NULL,
    anesthesia_type VARCHAR2(30 CHAR)   DEFAULT NULL,
    apply_doctor_id NUMBER(19)          NOT NULL,
    scheduled_time  TIMESTAMP           DEFAULT NULL,
    operating_room  VARCHAR2(50 CHAR)   DEFAULT NULL,
    status          VARCHAR2(20 CHAR)   DEFAULT 'PENDING' NOT NULL,
    remark          VARCHAR2(500 CHAR)  DEFAULT NULL,
    create_time     TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    update_time     TIMESTAMP           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_surgery_apply PRIMARY KEY (id)
);
CREATE INDEX idx_surgery_admission ON surgery_apply (admission_id);
CREATE INDEX idx_surgery_status ON surgery_apply (status);
COMMENT ON TABLE surgery_apply IS '手术申请表';

-- 4. medical_record_home 住院病案首页（出院归档）
CREATE TABLE medical_record_home (
    id                NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    admission_id      NUMBER(19)         NOT NULL,
    patient_id        NUMBER(19)         NOT NULL,
    department_id     NUMBER(19)         NOT NULL,
    doctor_id         NUMBER(19)         NOT NULL,
    admission_time    TIMESTAMP          NOT NULL,
    discharge_time    TIMESTAMP          NOT NULL,
    hospital_days     NUMBER(10)         DEFAULT 0 NOT NULL,
    discharge_diag    VARCHAR2(500 CHAR) NOT NULL,
    main_operation    VARCHAR2(200 CHAR) DEFAULT NULL,
    fee_bed           NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    fee_drug          NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    fee_exam          NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    fee_lab           NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    fee_other         NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    fee_total         NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    settlement_amount NUMBER(10,2)       DEFAULT 0.00 NOT NULL,
    create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_medical_record_home PRIMARY KEY (id),
    CONSTRAINT uk_home_admission UNIQUE (admission_id)
);
COMMENT ON TABLE medical_record_home IS '住院病案首页表';
