-- ============================================================
-- inpatient_db V3__surgery_center.sql（迭代10 F1~F5 手术/麻醉 轻量模拟）
-- 内容：
--   1. surgery            统一手术单（门诊 OUTPATIENT + 住院 INPATIENT 双来源）
--   2. preop_assessment   术前评估（ASA 分级 1~5，UNIQUE(surgery_id)）
--   3. informed_consent   知情同意书（SURGERY/ANESTHESIA 各一条）
--   4. surgery_record     手术记录（UNIQUE(surgery_id)）
--   5. anesthesia_record  麻醉记录（UNIQUE(surgery_id)，含三段生命体征 JSON）
--   6. seq_surgery_no     手术单号流水序列（SR + yyyyMMdd + 6 位流水）
-- 幂等：Oracle 无 IF NOT EXISTS，所有 CREATE TABLE / ALTER TABLE ADD COLUMN /
--       CREATE INDEX / CREATE SEQUENCE 收敛进 PL/SQL 块，按 user_tables /
--       user_tab_columns / user_indexes / user_sequences 探测后 EXECUTE IMMEDIATE
-- ============================================================

DECLARE
    v_cnt NUMBER := 0;
BEGIN

    -- ==================== 0. 手术单号流水序列 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'SEQ_SURGERY_NO';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_surgery_no START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    -- ==================== 1. surgery 统一手术单 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'SURGERY';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE surgery (
            id                  NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
            surgery_no          VARCHAR2(30 CHAR)  NOT NULL,
            source              VARCHAR2(20 CHAR)  DEFAULT ''OUTPATIENT'' NOT NULL,
            patient_id          NUMBER(19)         NOT NULL,
            apply_doctor_id     NUMBER(19)         DEFAULT NULL,
            surgery_name        VARCHAR2(200 CHAR) NOT NULL,
            surgery_type        VARCHAR2(50 CHAR)  DEFAULT NULL,
            scheduled_time      TIMESTAMP          DEFAULT NULL,
            operating_room      VARCHAR2(50 CHAR)  DEFAULT NULL,
            surgeon_id          NUMBER(19)         DEFAULT NULL,
            anesthesia_method   VARCHAR2(50 CHAR)  DEFAULT NULL,
            anesthesiologist_id NUMBER(19)         DEFAULT NULL,
            duration_min        NUMBER(6)          DEFAULT NULL,
            status              VARCHAR2(20 CHAR)  DEFAULT ''APPLIED'' NOT NULL,
            apply_id            NUMBER(19)         DEFAULT NULL,
            appointment_id      NUMBER(19)         DEFAULT NULL,
            notes               VARCHAR2(500 CHAR) DEFAULT NULL,
            create_time         TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            update_time         TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_surgery PRIMARY KEY (id),
            CONSTRAINT uk_surgery_no UNIQUE (surgery_no)
        )';
    END IF;
    -- 兜底补列（表已存在但缺列，如手工建库/部分回滚）
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
     WHERE table_name = 'SURGERY' AND column_name = 'APPOINTMENT_ID';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE surgery ADD (appointment_id NUMBER(19) DEFAULT NULL)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
     WHERE table_name = 'SURGERY' AND column_name = 'DURATION_MIN';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE surgery ADD (duration_min NUMBER(6) DEFAULT NULL)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_SURGERY_STATUS';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_surgery_status ON surgery (status)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_SURGERY_PATIENT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_surgery_patient ON surgery (patient_id)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_SURGERY_SCHED_TIME';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_surgery_sched_time ON surgery (scheduled_time)';
    END IF;
    SELECT COUNT(*) INTO v_cnt FROM user_indexes WHERE index_name = 'IDX_SURGERY_APPLY';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_surgery_apply ON surgery (apply_id)';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE surgery IS ''统一手术单表（门诊/住院双来源）''';
    -- 状态机注释：APPLIED(已建单待排台) → SCHEDULED(已排台) → PREOP_PASSED(术前评估通过)
    --             → IN_OPERATION(手术中) → OPERATED(手术完成)；APPLIED/SCHEDULED 可转 CANCELLED
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN surgery.status IS ''状态机: APPLIED-已建单(待排台) > SCHEDULED-已排台 > PREOP_PASSED-术前评估通过 > IN_OPERATION-手术中 > OPERATED-已完成; 另有 CANCELLED-已取消(仅 APPLIED/SCHEDULED 可取消)''';

    -- ==================== 2. preop_assessment 术前评估 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'PREOP_ASSESSMENT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE preop_assessment (
            id              NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
            surgery_id      NUMBER(19)          NOT NULL,
            asa_grade       VARCHAR2(10 CHAR)   DEFAULT NULL,
            risk_factors    VARCHAR2(500 CHAR)  DEFAULT NULL,
            assessment_text VARCHAR2(1000 CHAR) DEFAULT NULL,
            conclusion      VARCHAR2(20 CHAR)   DEFAULT NULL,
            assessor_id     NUMBER(19)          DEFAULT NULL,
            assessment_time TIMESTAMP           DEFAULT SYSDATE,
            create_time     TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_preop_assessment PRIMARY KEY (id),
            CONSTRAINT uk_preop_surgery UNIQUE (surgery_id)
        )';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE preop_assessment IS ''术前评估表（ASA 1~5 用数字字符存储，结论 PASSED/CONDITIONAL/REJECTED）''';

    -- ==================== 3. informed_consent 知情同意书 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'INFORMED_CONSENT';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE informed_consent (
            id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
            surgery_id   NUMBER(19)         NOT NULL,
            consent_type VARCHAR2(20 CHAR)  NOT NULL,
            patient_sign VARCHAR2(100 CHAR) DEFAULT NULL,
            signed_time  TIMESTAMP          DEFAULT NULL,
            witness      VARCHAR2(100 CHAR) DEFAULT NULL,
            create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_informed_consent PRIMARY KEY (id),
            CONSTRAINT uk_consent_surgery_type UNIQUE (surgery_id, consent_type)
        )';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE informed_consent IS ''知情同意书表（SURGERY-手术同意书 / ANESTHESIA-麻醉同意书，每单各一条）''';

    -- ==================== 4. surgery_record 手术记录 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'SURGERY_RECORD';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE surgery_record (
            id             NUMBER(19)          GENERATED BY DEFAULT AS IDENTITY,
            surgery_id     NUMBER(19)          NOT NULL,
            surgeon_id     NUMBER(19)          DEFAULT NULL,
            incision       VARCHAR2(100 CHAR)  DEFAULT NULL,
            procedure_text VARCHAR2(2000 CHAR) DEFAULT NULL,
            findings       VARCHAR2(1000 CHAR) DEFAULT NULL,
            specimen_flag  NUMBER(3)           DEFAULT 0,
            blood_loss_ml  NUMBER(8)           DEFAULT NULL,
            duration_min   NUMBER(6)           DEFAULT NULL,
            record_time    TIMESTAMP           DEFAULT SYSDATE,
            create_time    TIMESTAMP           DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_surgery_record PRIMARY KEY (id),
            CONSTRAINT uk_record_surgery UNIQUE (surgery_id)
        )';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE surgery_record IS ''手术记录表（specimen_flag 0-未送病理 1-已送病理）''';

    -- ==================== 5. anesthesia_record 麻醉记录 ====================
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'ANESTHESIA_RECORD';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE anesthesia_record (
            id                 NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
            surgery_id         NUMBER(19)         NOT NULL,
            method             VARCHAR2(50 CHAR)  DEFAULT NULL,
            asa_grade          VARCHAR2(10 CHAR)  DEFAULT NULL,
            induction_time     TIMESTAMP          DEFAULT NULL,
            reversal_time      TIMESTAMP          DEFAULT NULL,
            vitals_json        CLOB,
            anesthesiologist_id NUMBER(19)        DEFAULT NULL,
            notes              VARCHAR2(500 CHAR) DEFAULT NULL,
            create_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT pk_anesthesia_record PRIMARY KEY (id),
            CONSTRAINT uk_anesthesia_surgery UNIQUE (surgery_id)
        )';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON TABLE anesthesia_record IS ''麻醉记录表（vitals_json 为术前/术中/术后三组 BP/HR/SpO2 的 JSON 文本）''';

END;
/
