-- =====================================================================
-- 迭代 12：病案与统计（I2 上报登记 / I3 病案借阅归档 / J1 临床路径）
-- 幂等：所有 DDL 按 user_tables / user_sequences 探测后 EXECUTE IMMEDIATE
-- 注意：UNIQUE 约束自动创建同列唯一索引，不再另建同列普通索引（ORA-01408 教训）
-- =====================================================================

DECLARE
    v_cnt NUMBER;
BEGIN
    -- ---------- I2 report_form 传染病/不良事件上报 ----------
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'REPORT_FORM';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE report_form (
            id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            report_type       VARCHAR2(20 CHAR)  NOT NULL,
            patient_id        NUMBER,
            patient_name      VARCHAR2(50 CHAR),
            event_name        VARCHAR2(100 CHAR) NOT NULL,
            event_time        TIMESTAMP          DEFAULT SYSDATE,
            occur_department  VARCHAR2(50 CHAR),
            content           VARCHAR2(1000 CHAR),
            reporter_id       NUMBER,
            reporter_name     VARCHAR2(50 CHAR),
            status            VARCHAR2(20 CHAR)  DEFAULT ''SUBMITTED'' NOT NULL,
            review_note       VARCHAR2(300 CHAR),
            create_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT ck_report_form_type CHECK (report_type IN (''INFECTIOUS'', ''ADVERSE_EVENT'')),
            CONSTRAINT ck_report_form_status CHECK (status IN (''DRAFT'', ''SUBMITTED'', ''REVIEWED''))
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_report_form_type ON report_form (report_type, status)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_report_form_patient ON report_form (patient_id)';
    END IF;

    -- ---------- I3 medical_record 病案 ----------
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'MEDICAL_RECORD';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE medical_record (
            id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            record_no      VARCHAR2(30 CHAR)  NOT NULL,
            patient_id     NUMBER             NOT NULL,
            patient_name   VARCHAR2(50 CHAR),
            admission_id   NUMBER,
            diagnosis      VARCHAR2(200 CHAR),
            archive_status VARCHAR2(20 CHAR)  DEFAULT ''IN_WARD'' NOT NULL,
            archive_time   TIMESTAMP,
            create_time    TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT uk_medical_record_no UNIQUE (record_no),
            CONSTRAINT ck_medical_record_arch CHECK (archive_status IN (''IN_WARD'', ''ARCHIVED''))
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_medical_record_patient ON medical_record (patient_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_medical_record_arch ON medical_record (archive_status)';
    END IF;

    -- ---------- I3 record_borrow 借阅 ----------
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'RECORD_BORROW';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE record_borrow (
            id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            record_id          NUMBER             NOT NULL,
            borrower_id        NUMBER,
            borrower_name      VARCHAR2(50 CHAR),
            purpose            VARCHAR2(200 CHAR),
            borrow_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            expect_return_time TIMESTAMP,
            return_time        TIMESTAMP,
            status             VARCHAR2(20 CHAR)  DEFAULT ''BORROWED'' NOT NULL,
            CONSTRAINT ck_record_borrow_status CHECK (status IN (''BORROWED'', ''RETURNED''))
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_record_borrow_record ON record_borrow (record_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_record_borrow_status ON record_borrow (status)';
    END IF;

    -- ---------- J1 path_template 路径模板 ----------
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'PATH_TEMPLATE';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE path_template (
            id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            path_code     VARCHAR2(30 CHAR)  NOT NULL,
            path_name     VARCHAR2(100 CHAR) NOT NULL,
            disease_name  VARCHAR2(100 CHAR),
            standard_days NUMBER(3)          DEFAULT 1 NOT NULL,
            total_estimate NUMBER(10,2)      DEFAULT 0,
            item_json     CLOB,
            status        NUMBER(3)          DEFAULT 1 NOT NULL,
            create_time   TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            CONSTRAINT uk_path_template_code UNIQUE (path_code)
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_path_template_disease ON path_template (disease_name)';
    END IF;

    -- ---------- J1 patient_path 患者路径 ----------
    SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'PATIENT_PATH';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE patient_path (
            id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            template_id      NUMBER             NOT NULL,
            admission_id     NUMBER             NOT NULL,
            patient_id       NUMBER,
            enter_time       TIMESTAMP          DEFAULT SYSDATE NOT NULL,
            current_day      NUMBER(3)          DEFAULT 1 NOT NULL,
            status           VARCHAR2(20 CHAR)  DEFAULT ''IN_PATH'' NOT NULL,
            variation_reason VARCHAR2(300 CHAR),
            exit_time        TIMESTAMP,
            CONSTRAINT ck_patient_path_status CHECK (status IN (''IN_PATH'', ''VARIATION'', ''EXITED'', ''COMPLETED''))
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_patient_path_admission ON patient_path (admission_id)';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_patient_path_status ON patient_path (status)';
    END IF;

    -- ---------- 病案号序列 ----------
    SELECT COUNT(*) INTO v_cnt FROM user_sequences WHERE sequence_name = 'SEQ_RECORD_NO';
    IF v_cnt = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_record_no START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;

    COMMIT;
END;
