-- =====================================================================
-- V3: 迭代15 B1 排床优化方案（inpatient）
-- 幂等：user_tables 探测后建表
-- =====================================================================

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM user_tables WHERE table_name = 'BED_ASSIGN_PLAN';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE '
    CREATE TABLE bed_assign_plan (
      id            NUMBER(19)       GENERATED BY DEFAULT AS IDENTITY,
      plan_no       VARCHAR2(32 CHAR) NOT NULL,
      plan_date     DATE             NOT NULL,
      suggestions   CLOB,
      matched_cnt   NUMBER(10)       DEFAULT 0 NOT NULL,
      unmatched_cnt NUMBER(10)       DEFAULT 0 NOT NULL,
      create_time   TIMESTAMP        DEFAULT SYSDATE NOT NULL,
      CONSTRAINT pk_bed_assign_plan PRIMARY KEY (id),
      CONSTRAINT uq_bed_plan_no UNIQUE (plan_no)
    )';
  END IF;
END;
/
