-- ============================================================
-- auth_db V1__init.sql（Oracle 19c 版，迭代6.5 MySQL→Oracle 迁移）
-- 认证授权中心：6 张表 + 初始数据（3 角色 + 1 管理员 + 1 关联）
-- 迁移规则：AUTO_INCREMENT→IDENTITY(BY DEFAULT)、DATETIME→TIMESTAMP、
--           TINYINT→NUMBER(3)、TEXT→CLOB、VARCHAR→VARCHAR2(n CHAR)、
--           表名 user→sys_user（user 为 Oracle 保留字）、内联列注释移除
-- ============================================================

-- ==================== 1. sys_user（用户表） ====================
CREATE TABLE sys_user (
    id                    NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    phone                 VARCHAR2(20 CHAR)  NOT NULL,
    password              VARCHAR2(255 CHAR) NOT NULL,
    real_name             VARCHAR2(50 CHAR)  NOT NULL,
    gender                NUMBER(3)          DEFAULT 0,
    user_type             VARCHAR2(20 CHAR)  NOT NULL,
    status                NUMBER(3)          DEFAULT 1,
    last_login_time       TIMESTAMP          DEFAULT NULL,
    last_login_ip         VARCHAR2(50 CHAR)  DEFAULT NULL,
    need_password_change  NUMBER(3)          DEFAULT 0,
    create_time           TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time           TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    deleted               NUMBER(3)          DEFAULT 0,
    CONSTRAINT pk_sys_user PRIMARY KEY (id),
    CONSTRAINT uk_user_phone UNIQUE (phone)
);
CREATE INDEX idx_user_type ON sys_user (user_type);
CREATE INDEX idx_user_status ON sys_user (status);
COMMENT ON TABLE sys_user IS '用户表';

-- ==================== 2. role（角色表） ====================
CREATE TABLE role (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    role_code    VARCHAR2(50 CHAR)  NOT NULL,
    role_name    VARCHAR2(100 CHAR) NOT NULL,
    description  VARCHAR2(255 CHAR) DEFAULT NULL,
    status       NUMBER(3)          DEFAULT 1,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT uk_role_code UNIQUE (role_code)
);
COMMENT ON TABLE role IS '角色表';

-- ==================== 3. permission（权限表） ====================
CREATE TABLE permission (
    id           NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    perm_code    VARCHAR2(100 CHAR) NOT NULL,
    perm_name    VARCHAR2(100 CHAR) NOT NULL,
    perm_type    VARCHAR2(20 CHAR)  NOT NULL,
    parent_id    NUMBER(19)         DEFAULT 0,
    path         VARCHAR2(255 CHAR) DEFAULT NULL,
    sort_order   NUMBER(10)         DEFAULT 0,
    status       NUMBER(3)          DEFAULT 1,
    create_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time  TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_permission PRIMARY KEY (id),
    CONSTRAINT uk_perm_code UNIQUE (perm_code)
);
CREATE INDEX idx_perm_parent ON permission (parent_id);
COMMENT ON TABLE permission IS '权限表';

-- ==================== 4. user_role（用户角色关联表） ====================
CREATE TABLE user_role (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    user_id      NUMBER(19) NOT NULL,
    role_id      NUMBER(19) NOT NULL,
    create_time  TIMESTAMP  DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id),
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id)
);
COMMENT ON TABLE user_role IS '用户角色关联表';

-- ==================== 5. role_permission（角色权限关联表） ====================
CREATE TABLE role_permission (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    role_id        NUMBER(19) NOT NULL,
    permission_id  NUMBER(19) NOT NULL,
    create_time    TIMESTAMP  DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (id),
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
);
COMMENT ON TABLE role_permission IS '角色权限关联表';

-- ==================== 6. audit_log（操作审计日志表） ====================
CREATE TABLE audit_log (
    id               NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    user_id          NUMBER(19)         DEFAULT NULL,
    username         VARCHAR2(50 CHAR)  DEFAULT NULL,
    operation        VARCHAR2(100 CHAR) NOT NULL,
    http_method      VARCHAR2(10 CHAR)  DEFAULT NULL,
    request_uri      VARCHAR2(255 CHAR) DEFAULT NULL,
    request_ip       VARCHAR2(50 CHAR)  DEFAULT NULL,
    request_params   CLOB,
    response_result  CLOB,
    execution_time   NUMBER(19)         DEFAULT NULL,
    status           NUMBER(3)          DEFAULT 1,
    error_message    VARCHAR2(500 CHAR) DEFAULT NULL,
    create_time      TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);
CREATE INDEX idx_audit_user_id ON audit_log (user_id);
CREATE INDEX idx_audit_create_time ON audit_log (create_time);
CREATE INDEX idx_audit_operation ON audit_log (operation);
COMMENT ON TABLE audit_log IS '操作审计日志表';

-- ==================== 初始数据 ====================

-- 预置角色（Oracle 19c 不支持多行 VALUES，拆为多条 INSERT）
INSERT INTO role (role_code, role_name, description) VALUES ('ROLE_ADMIN',   '管理员', '平台超级管理员，拥有全部权限');
INSERT INTO role (role_code, role_name, description) VALUES ('ROLE_DOCTOR',  '医生',   '门诊医生，负责接诊与叫号');
INSERT INTO role (role_code, role_name, description) VALUES ('ROLE_PATIENT', '患者',   '患者用户，通过小程序挂号就诊');

-- 预置管理员账户（密码为 "admin123" 的 BCrypt 哈希）
INSERT INTO sys_user (phone, password, real_name, gender, user_type, status, need_password_change)
VALUES ('13800000000', '$2a$12$G9OpjHlTW2dTR/vomvrsQ.BjTtUT3MjI6ordDptw/DnPG0rGzmMna', '系统管理员', 0, 'ADMIN', 1, 1);

-- 预置用户角色关联（管理员拥有 ADMIN 角色）
INSERT INTO user_role (user_id, role_id) VALUES (1, 1);
