-- ============================================================
-- V9：数据范围跨科室申请 data_scope_apply（Oracle 版，迭代 5 阶段 3）
-- 说明：
--   1. 新建 data_scope_apply 表：用户提交跨科室数据访问申请 → 科主任/管理员/超管审批。
--   2. 数据范围默认规则（不落表，由代码 DataScopeUtil 解析）：
--      超管/管理员=全量；收费员/分诊护士=全院；科主任=本科室；医师=本人病历/处方；
--      影像/检验技师=本科室申请单；护士=本输液室；患者=本人。
--   3. 审批通过后给用户临时/长期跨科室授权（授权记录即本表 APPROVED 行）。
--   4. 权限码：api:auth:data-scope:apply（申请，绑定业务角色）、
--      api:auth:data-scope:approve（审批，绑定超管/管理员/科主任）、
--      api:auth:data-scope:list（本人申请列表，全部登录用户）。
-- 迁移：IF NOT EXISTS 由 Flyway 单次执行语义替代；内层 SELECT 补 FROM dual
-- ============================================================

-- ==================== 1. data_scope_apply 表 ====================
CREATE TABLE data_scope_apply (
    id                      NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    user_id                 NUMBER(19)         NOT NULL,
    user_name               VARCHAR2(50 CHAR)  NOT NULL,
    target_department_id    NUMBER(19)         NOT NULL,
    target_department_name  VARCHAR2(100 CHAR) DEFAULT NULL,
    reason                  VARCHAR2(500 CHAR) NOT NULL,
    status                  VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    approver_id             NUMBER(19)         DEFAULT NULL,
    approver_name           VARCHAR2(50 CHAR)  DEFAULT NULL,
    approve_comment         VARCHAR2(500 CHAR) DEFAULT NULL,
    expire_time             TIMESTAMP          DEFAULT NULL,
    apply_time              TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    approve_time            TIMESTAMP          DEFAULT NULL,
    create_time             TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time             TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_data_scope_apply PRIMARY KEY (id)
);
CREATE INDEX idx_dsa_user_status ON data_scope_apply (user_id, status);
CREATE INDEX idx_dsa_dept_status ON data_scope_apply (target_department_id, status);
COMMENT ON TABLE data_scope_apply IS '跨科室数据范围申请表';

-- ==================== 2. 数据范围权限码 ====================
INSERT INTO permission (perm_code, perm_name, perm_type, parent_id, path, sort_order, status)
SELECT tmp.perm_code, tmp.perm_name, 'API', 0, NULL, tmp.sort_order, 1
FROM (
    SELECT 'api:auth:data-scope:apply'    AS perm_code, '提交跨科室申请' AS perm_name, 1050 AS sort_order FROM dual UNION ALL
    SELECT 'api:auth:data-scope:approve'  , '审批跨科室申请', 1051 FROM dual UNION ALL
    SELECT 'api:auth:data-scope:list'     , '跨科室申请列表', 1052 FROM dual
) tmp
WHERE NOT EXISTS (SELECT 1 FROM permission p WHERE p.perm_code = tmp.perm_code);

-- ==================== 3. 权限绑定 ====================
-- 3.1 申请：业务角色（科主任/医师/影像技师/检验技师/护士/分诊护士/药师）+ 超管/管理员（管理员可代提）
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM role r
JOIN permission p ON p.perm_code = 'api:auth:data-scope:apply'
WHERE r.role_code IN ('ROLE_DEPT_CHIEF','ROLE_DOCTOR','ROLE_EXAM_TECH','ROLE_LAB_TECH',
                      'ROLE_NURSE','ROLE_TRIAGE_NURSE','ROLE_PHARMACIST','ROLE_SUPER_ADMIN','ROLE_ADMIN')
  AND NOT EXISTS (SELECT 1 FROM role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);

-- 3.2 审批：超管/管理员/科主任（科室负责人审批本科室或跨科室申请）
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM role r
JOIN permission p ON p.perm_code = 'api:auth:data-scope:approve'
WHERE r.role_code IN ('ROLE_SUPER_ADMIN','ROLE_ADMIN','ROLE_DEPT_CHIEF')
  AND NOT EXISTS (SELECT 1 FROM role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);

-- 3.3 本人列表：全部角色（含患者）
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM role r
JOIN permission p ON p.perm_code = 'api:auth:data-scope:list'
WHERE NOT EXISTS (SELECT 1 FROM role_permission rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);
