-- ============================================================
-- patient_db V1__init.sql（Oracle 19c 版，迭代6.5 迁移）
-- 患者档案中心：3 张表
-- ============================================================

-- ==================== 1. patient（患者电子档案表） ====================
CREATE TABLE patient (
    id                 NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    user_id            NUMBER(19)         DEFAULT NULL,
    name               VARCHAR2(50 CHAR)  NOT NULL,
    gender             NUMBER(3)          DEFAULT 0,
    birth_date         DATE               DEFAULT NULL,
    id_card            VARCHAR2(18 CHAR)  DEFAULT NULL,
    phone              VARCHAR2(20 CHAR)  NOT NULL,
    emergency_contact  VARCHAR2(50 CHAR)  DEFAULT NULL,
    emergency_phone    VARCHAR2(20 CHAR)  DEFAULT NULL,
    verify_status      NUMBER(3)          DEFAULT 0,
    id_card_front_url  VARCHAR2(500 CHAR) DEFAULT NULL,
    id_card_back_url   VARCHAR2(500 CHAR) DEFAULT NULL,
    verify_comment     VARCHAR2(255 CHAR) DEFAULT NULL,
    avatar_url         VARCHAR2(500 CHAR) DEFAULT NULL,
    create_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    update_time        TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_patient PRIMARY KEY (id)
);
CREATE INDEX idx_patient_user_id ON patient (user_id);
CREATE INDEX idx_patient_id_card ON patient (id_card);
CREATE INDEX idx_patient_phone ON patient (phone);
CREATE INDEX idx_patient_verify_status ON patient (verify_status);
COMMENT ON TABLE patient IS '患者电子档案表';

-- ==================== 2. visit_card（虚拟就诊卡表） ====================
CREATE TABLE visit_card (
    id          NUMBER(19)        GENERATED BY DEFAULT AS IDENTITY,
    patient_id  NUMBER(19)        NOT NULL,
    card_no     VARCHAR2(20 CHAR) NOT NULL,
    status      NUMBER(3)         DEFAULT 1,
    issue_date  DATE              NOT NULL,
    create_time TIMESTAMP         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_visit_card PRIMARY KEY (id),
    CONSTRAINT uk_card_no UNIQUE (card_no)
);
CREATE INDEX idx_card_patient_id ON visit_card (patient_id);
COMMENT ON TABLE visit_card IS '虚拟就诊卡表';

-- ==================== 3. allergy（过敏史表） ====================
CREATE TABLE allergy (
    id               NUMBER(19)         GENERATED BY DEFAULT AS IDENTITY,
    patient_id       NUMBER(19)         NOT NULL,
    allergen         VARCHAR2(100 CHAR) NOT NULL,
    reaction_type    VARCHAR2(50 CHAR)  DEFAULT NULL,
    severity         VARCHAR2(20 CHAR)  DEFAULT NULL,
    source           VARCHAR2(20 CHAR)  DEFAULT 'PATIENT' NOT NULL,
    source_doctor_id NUMBER(19)         DEFAULT NULL,
    create_time      TIMESTAMP          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_allergy PRIMARY KEY (id)
);
CREATE INDEX idx_allergy_patient_id ON allergy (patient_id);
COMMENT ON TABLE allergy IS '过敏史表';
